#!/bin/bash

DOUBLE_DEFINED_FUNCS=$(ack "^\s*(async)?\s*function\s*" *.js | grep -v "cosmo_ok" | grep -v "asanai.js" | sed -e "s#.*\s*function\s*##" | sed -e "s#\s*(.*##" | sort | uniq -c | sort -nr | tac | egrep -v "^\s*[0-9]+\s*$" | egrep -v "^\s*1\s+.*$")

if [[ ! -z $DOUBLE_DEFINED_FUNCS ]]; then
	echo "find double defined functions"
	echo $DOUBLE_DEFINED_FUNCS
	exit 1
fi

exit 0
