#!/bin/bash

for i in $(grep "language.lang..\"" *.js | sed -e 's#.*lang.."##' | sed -e 's#".*##' | sort | uniq); do
	cat translations.php | grep -q $i || echo "$i not found in translations.php"
done
