#!/bin/bash

for test in tests/find_*; do
	if ! echo "$test" | egrep -q "find_unwrapped_base_functions|find_double_defined_functions"; then
		echo "Testing $test..."
		if ! "$test"; then
			echo "$test failed"
			exit 1
		fi

		echo "-> $test OK"
	fi
done

echo "Smoke tests passed"
exit 0
