#!/bin/bash

for test in tests/find_*; do
	if ! echo "$test" | grep -q "find_double_defined_functions"; then
		echo "Testing $test..."
		if ! "$test"; then
			echo "$test failed"
			exit 1
		fi
	fi
done

echo "Smoke tests passed"
exit 0
