<?php include_once("functions.php"); ?>
<!--
COURSE_METADATA:
title: Diffusion Models
description: How Denoising Diffusion Probabilistic Models (DDPM) and Latent Diffusion (Stable Diffusion) generate images by reversing noise.
icon: &#127912;
part: 4
order: 28
color: sky
topics: multimodal, vision, architecture, programming
-->

<div class="md">
<figure style="margin: 1em 0 1.5em 0;">
	<img style="width: 100%; height: auto; display: block; border-radius: 6px;" src="diffusion_astronaut.webp" alt="An astronaut riding a horse — an image generated by Stable Diffusion 3.5 from the text prompt 'a photograph of an astronaut riding a horse'" />
	<figcaption>A single text prompt, and a diffusion model produced this image in seconds. This one was created with the prompt "Astronaut Riding a Horse" (\cite[Image: Stable Diffusion 3.5]{diffusion_astronaut_img})</figcaption>
</figure>

Most of AI's image generators used to be delicate. GANs collapsed, VAEs blurred, and training them was an art. Then in 2020, a paper called **DDPM** \cite[Ho et al., 2020]{ho2020ddpm} — built on a 2019 idea from Yang Song and Stefano Ermon \cite[Song & Ermon, 2019]{song2019score} — quietly opened a new path. Within two years, Stable Diffusion, DALL·E 2, Imagen, and Midjourney had made **diffusion** the dominant way to generate images. By 2024 it had spread to video (Sora, Veo), audio, music, and even 3D protein structures.

The idea is almost paradoxical: instead of generating an image in one forward pass, **destroy an image with noise step by step, then learn to undo the destruction, one tiny step at a time**. It is a different paradigm from the autoregressive next-token prediction that drives LLMs, even though both produce staggering results.

## The central trick: destroy, then learn to undo

Imagine dropping a clear photograph into a glass of water and slowly stirring in drops of black ink. After each drop the picture becomes a little less recognizable. After enough drops, all you see is uniform grey.

Now imagine the reverse: starting with grey water, learn to *remove* exactly the right amount of ink, drop by drop, until a coherent photograph reappears. If you can learn that reverse process well enough, you can start from *any* grey water and turn it into a fresh, novel photograph.

That is what a diffusion model does. The forward process (ink going in) is a hand-designed procedure with no learned parameters. The reverse process (ink coming out) is what a neural network has to learn.
</div>

<div class="md">
## The forward process: a controlled demolition

Concretely, the forward process takes a clean image $x_0$ and at each of $T$ small timesteps sprinkles in a little Gaussian noise. After $T = 1000$ steps nothing of the original picture survives.

A handy mathematical shortcut is that at any intermediate timestep $t$, you can jump straight from the clean image to $x_t$ in one go, without stepping through all the intermediate $x_1, x_2, \ldots, x_{t-1}$:

$$
x_t \;=\; \sqrt{1-t}\, x_0 \;+\; \sqrt{t}\, \epsilon, \qquad \epsilon \sim \mathcal{N}(0, \mathbf{I})
$$

For $t = 1$ the first term vanishes and $x_T$ is pure Gaussian noise. Crucially, **every step of the forward process is fixed in advance** — no learning required. The forward chain is just a way to manufacture training data for the model that does the hard work.

The slider below shows the forward process happening to a real image. Drag it to watch the picture dissolve into noise.
</div>

<div id="forward-slider" style="max-width: 512px; margin: 1em auto; text-align: center;"></div>

<div class="md">
## The reverse process: the part that learns

The reverse process starts from pure noise and runs backward. At each step, the network looks at the current noisy image and asks: *what noise should I subtract to make this slightly more recognizable?* A thousand such tiny denoising steps, and out pops a clean image.

This is the formulation introduced by DDPM. The training objective is almost laughably simple. For a randomly chosen timestep $t$:

1. Take a real image $x_0$.
2. Add the corresponding amount of noise, producing a noisy $x_t$.
3. Ask the network to predict *what that noise was*.
4. Train by mean-squared error between the predicted and the true noise.

For the vanilla DDPM / DDIM recipe that is it: no discriminator, no generator, no min-max game. Just MSE between predicted and true noise. This stability is one of the big reasons diffusion displaced GANs so quickly. (One caveat: the 1-step "Turbo" models like SDXL-Turbo were *not* trained with pure MSE — they use **adversarial diffusion distillation**, an explicit GAN-style loss, to compress 50 denoising steps into 1.)

The slider below steps through the **reverse** process on the same image. Drag it from right to left to watch an image emerge from chaos. In a real diffusion model this would take a thousand tiny denoising steps; here we collapse them into a handful of frames.
</div>

<div id="reverse-slider" style="max-width: 512px; margin: 1em auto; text-align: center;"></div>

<div class="md">
## Why does this work?

You might ask: how can *removing noise* ever create a picture? The trick is this — **a denoiser that can spot noise must also have learned what "no noise" looks like**. It has implicitly learned the shape of the data distribution. So if you start from pure noise and repeatedly denoise, you trace a path through that distribution, and end up with a brand new sample.

That is the deep "why" of diffusion in one sentence. Two ways to make it more concrete:

* **Coarse-to-fine**: at high noise levels, only the largest-scale structure of the data is recoverable. The network first sketches rough shapes, then refines detail. Generation is hierarchical *by construction*.
* **Score matching** \cite[Song & Ermon, 2019]{song2019score}: a denoiser that can predict the noise in any image is mathematically equivalent to a model that knows the gradient of the data distribution — the "score". Following that gradient (with a little randomness, a recipe called Langevin dynamics) is equivalent to sampling from the data distribution.

Either view explains why "denoising" and "generation" are two sides of the same coin.
</div>

<div class="md">
## Telling the model what to draw

To make a model draw *what you want*, you have to feed it some signal. For text-to-image, that signal is a text prompt, first encoded into a vector by a separate text encoder (typically CLIP or T5).

The trick that made text-to-image *actually work* is **classifier-free guidance** \cite[Ho & Salimans, 2022]{ho2022cfg}. At training time, the network is shown the text prompt 90% of the time and *nothing* 10% of the time, learning both a conditional and an unconditional denoiser in one model. At inference, you amplify the gap between them:

$$
\tilde\epsilon_\theta(x_t, t, c) \;=\; \epsilon_\theta(x_t, t, \varnothing) \;+\; w \cdot \big(\epsilon_\theta(x_t, t, c) - \epsilon_\theta(x_t, t, \varnothing)\big)
$$

The factor $w$ is the **guidance scale**. The intuition: $\epsilon_\theta(x_t, t, \varnothing)$ is what the model thinks "an image" looks like; $\epsilon_\theta(x_t, t, c) - \epsilon_\theta(x_t, t, \varnothing)$ is the *direction* the prompt pushes in; multiplying by $w > 1$ moves the output further along that direction, so the generated image matches the prompt more literally. Around $w \approx 7$ is the modern default. Higher values follow the prompt more literally but produce more generic-looking images; lower values give variety but may drift from the prompt.
</div>

<div class="md">
## From text to image: the whole pipeline

The CFG trick above answers "how do you amplify the prompt". But three questions remain: **where do the (image, prompt) training pairs come from?**, **how does the text encoder turn words into something the U-Net can read?**, and **how does the U-Net actually use those numbers?** This section walks through the full pipeline end-to-end.

### 1. Training data — no manual labels needed

You do **not** need to sit down and label 100,000 images. The training set for Stable Diffusion is **LAION-5B**, a publicly released scrape of about 5 billion (image, alt-text) pairs from the web. The "label" of every image is whatever its surrounding HTML already said — the alt attribute, the caption, the page title.

What the model actually learns from this data is **not a database of specific images**. It learns an *internal representation of the world*: what astronauts look like, what horses look like, what "riding" looks like, what "in space" looks like — each concept distilled from many thousands of images seen during training. When you prompt for "an astronaut riding a horse", there is almost certainly no training image of exactly that scene. The model composes a new image by combining its learned concepts: astronaut-shape here, horse-shape there, riding-pose between them. The output is **synthesized**, not retrieved.

This is also why diffusion models sometimes hallucinate or get details wrong: the "labels" are noisy, scraped web text, not clean annotations, and the concepts are statistical, not encyclopedic.

(One consequence worth knowing: as more AI-generated images flood the web, future models trained on the same web will be trained on their own predecessors' outputs. This recursive phenomenon is called **model collapse**, and it is a real research concern.)
</div>

<div id="tokenizer-viz" style="max-width: 880px; margin: 1em auto;"></div>

<div class="md">
### 2. Text becomes numbers — the text encoder and embeddings

The diffusion U-Net cannot read English. Before it ever sees your prompt, a separate **text encoder** turns the prompt into a sequence of vectors. For Stable Diffusion 1.5, that encoder is CLIP's text tower; for SD 3 and FLUX, it is T5. Both are **Transformer encoders** — the same architecture family as the LLMs in the other chapters.

The text encoder does two things, in order — tokenization and embedding. Both are covered in detail elsewhere on this site (see the **Tokenization** and **Embeddings** chapters); the small viz above is just a quick reminder of what comes out of the other end of that pipeline. The crucial property for our purposes is that each token ends up as a vector (768 numbers for CLIP, 4096 for T5-XXL), and **similar concepts end up close together** in that vector space: "astronaut" and "space suit" have nearby vectors, "horse" and "pony" have nearby vectors, "astronaut riding a horse" is far from "still life with fruit".
</div>

<div class="md">
### 3. Cross-attention — how the U-Net reads the text

Now the diffusion U-Net has two inputs at every denoising step:

* the current noisy image (as a grid of patches, e.g. $8 \times 8$)
* the text embedding (a sequence of vectors, one per token)

The U-Net applies **cross-attention** at each layer. The picture to keep in your head: **at every step, the model paints the image by asking each word in your prompt, "which part of the picture is yours?"** The word *"astronaut"* claims the upper-center region. The word *"horse"* claims the lower region. The word *"riding"* claims the bit in between. Function words like *"a"*, *"of"* barely claim anything.

Below: click any *content* word in the prompt and watch a colored region light up over the part of the astronaut image that word would "claim" during generation. The regions are simplified — a real diffusion model has hundreds of tiny patches — but the principle is the same: each word in your prompt controls its own piece of the picture.
</div>

<div id="cross-attention-viz" style="max-width: 880px; margin: 1em auto;"></div>

<div class="md">
This is the mechanism behind every text-to-image model. Different words control different regions. By the end of denoising, each pixel of the image has been "asked" which word it should look like, and the text embedding has answered. **If you swap one word in the prompt, the embedding moves, the attention shifts, and the generated image changes in just that region.**
</div>
The full Stable Diffusion pipeline looks like this end-to-end:

<figure style="max-width:880px; margin:1.5em auto; text-align:center;">
	<img src="diffusion_architecture.png" alt="Diagram of the Stable Diffusion latent diffusion architecture, showing the text encoder, U-Net denoiser with cross-attention, and VAE encoder/decoder" style="width:100%; height:auto; border-radius:6px;" />
	<figcaption>The Stable Diffusion pipeline: a text encoder turns your prompt into vectors, the U-Net denoises a latent tensor conditioned on those vectors (via cross-attention), and a frozen VAE decoder turns the clean latent back into pixels. \cite[Image: Stable Diffusion architecture]{diffusion_architecture_img}</figcaption>
</figure>

So the answer to "do I need to label 100k images?" is: **no** for pretraining (the labels already exist on the web). The yes cases are *fine-tuning* — if you want the model to draw a specific style or subject, you can fine-tune with **LoRA** \cite[Hu et al., 2021]{hu2021lora} on as few as a few dozen images, or steer outputs with **ControlNet** \cite[Zhang et al., 2023]{zhang2023controlnet} using edge maps, depth maps, or pose skeletons.
</div>

<div class="md">
## What's the network?

It is **not** a stack of dense layers. The denoiser is a **U-Net** built from:

* **2D convolutions** — slide filters over the latent to detect local patterns
* **ResBlocks** — `Conv → Norm → SiLU → Conv` plus a skip connection
* **GroupNorm + SiLU** — normalization and the smooth $x \cdot \sigma(x)$ activation
* **Self-attention** at the lower resolutions — pixels talk to each other across the whole image
* **Cross-attention** at the lower resolutions — pixels attend to the text tokens (this is the conditioning)
* **Skip connections** from each encoder block to the matching decoder block
* **Sinusoidal time embedding** for the timestep $t$, injected into every block

The only fully-connected layers are tiny MLPs for the time and text embeddings. Everything else is convolution or attention. Stable Diffusion 1.5 has ~860 M parameters. The forward pass per denoising step: encode $t$, run the noisy latent down through four encoder blocks, apply self- and cross-attention at the bottleneck, run back up through four decoder blocks with skip connections, output the predicted noise.

</div>

<div class="md">
## Stable Diffusion: doing it in a compressed space

Doing all this in raw pixel space at $512 \times 512$ resolution is brutally expensive. Each image is roughly 786,000 numbers, and the network must process hundreds of millions of them per step.

The breakthrough of **Latent Diffusion Models** \cite[Rombach et al., 2022]{rombach2022ldm} — the technology behind Stable Diffusion — was to *first* compress the image into a much smaller latent representation using a pretrained autoencoder, *then* do all the diffusion work in that compressed space, *then* decode the result back to pixels. The U-Net never sees a pixel; it only sees a $64 \times 64$ latent map. This makes training and inference roughly 64× cheaper.

The text prompt goes through CLIP, the latent goes through the U-Net, and at the end a frozen VAE decoder turns the clean latent back into an image. The VAE is never trained alongside the diffusion model — it was learned earlier as an ordinary autoencoder and frozen in place.

Below, the famous DDIM denoising sequence for a real Stable Diffusion run shows the same idea in action. Read it from top-left to bottom-right: the network starts from pure noise and gradually reveals a coherent image of a European-style castle in Japan, adding detail with each step.

<figure style="max-width:100%; margin:1.5em auto; text-align:center;">
	<img src="diffusion_ddim_steps.jpg" alt="An X/Y plot of denoising steps showing a European-style castle in Japan becoming progressively more detailed as noise is removed, generated using Stable Diffusion V1-5 with DDIM sampling" style="width:100%; height:auto; border-radius:6px;" />
	<figcaption>Each frame is one denoising step of a Stable Diffusion 1.5 model using DDIM sampling. Early steps establish rough shapes and color fields; later steps refine texture and fine detail. \cite[Image: DDIM denoising steps]{diffusion_ddim_img}</figcaption>
</figure>
</div>

<div class="md">
## Beyond images

The same recipe works anywhere you can define a "noising" process and a network that can reverse it:

* **Video**: Sora, Veo, Stable Video Diffusion — same idea, with an extra time dimension and attention layers that keep frames consistent.
* **Audio**: AudioLDM, DiffSinger — diffuse a spectrogram, then a vocoder turns it back into sound.
* **Music**: Riffusion, MusicLDM.
* **Proteins**: RFdiffusion, Chroma — diffuse over 3D atomic coordinates of new proteins.
* **Robotics**: Diffuser — diffuse over action sequences.
* **Time-series**: TimeGrad — diffuse over weather, financial, or sensor data.

The general principle is almost embarrassingly simple: **if you can blur it, you can unblur it; and if you can unblur it, you can generate it from scratch.**
</div>

<div class="md">
## Where the field is now

By 2025, the diffusion community has largely moved on to **flow matching** \cite[Lipman et al., 2023]{lipman2023flow} — a more general framework where the "noising" path between data and noise can be a straight line instead of a curved one. FLUX, Stable Diffusion 3, and most 2024+ models use it.

The dominant backbone is no longer the U-Net but the **Diffusion Transformer (DiT)** \cite[Peebles & Xie, 2023]{peebles2023dit} — a vanilla Vision Transformer scaled up. Sora, FLUX, and Stable Diffusion 3 all use DiT-style backbones. The pattern is familiar: U-Net worked, then Transformers worked better once they were big enough.

Practical models have also become fast. Modern systems generate images in **1–8 network evaluations** through clever solvers (DPM-Solver, EDM) and adversarial distillation (SDXL-Turbo, LCM). Diffusion is no longer slow.

In five years, the technique went from "diffusion as a curiosity" to "diffusion as the universal generative recipe" for images, video, audio, and molecules.
</div>

<div class="md">
## Try it yourself

These are the tools the diffusion community actually uses:

* **[Stable Diffusion Web UI (AUTOMATIC1111)](https://github.com/AUTOMATIC1111/stable-diffusion-webui)** — the de facto local frontend. One install, full access to SD 1.5, SDXL, and the entire community of fine-tunes.
* **[ComfyUI](https://github.com/comfyanonymous/ComfyUI)** — node-based, scriptable, the choice of power users. Best for pipelines that mix ControlNet, LoRA, img2img, inpainting and upscaling.
* **[Fooocus](https://github.com/lllyasviel/Fooocus)** — minimal UI inspired by Midjourney. Best if you want results without fiddling.
* **[Hugging Face Spaces](https://huggingface.co/spaces)** — free browser-based demos of the latest open models. No installation, no GPU needed.
* **[InvokeAI](https://github.com/invoke-ai/InvokeAI)** — a polished commercial-grade CLI and web UI.

For *controlling* what the model draws:

* **[ControlNet](https://github.com/lllyasviel/ControlNet)** \cite[Zhang et al., 2023]{zhang2023controlnet} — spatial control from edge maps, depth maps, or pose skeletons, without retraining the base model.
* **LoRA** \cite[Hu et al., 2021]{hu2021lora} — small adapters that fine-tune the U-Net's attention layers on a few hundred images of your own style, in minutes on a single GPU. ([paper](https://arxiv.org/abs/2106.09685))

If you would rather read the foundational papers, the trio that started it all is Sohl-Dickstein's 2015 thermodynamic framing \cite[Sohl-Dickstein et al., 2015]{sohl2015deep}, Song & Ermon's score-based 2019 paper \cite[Song & Ermon, 2019]{song2019score}, and Ho's DDPM in 2020 \cite[Ho et al., 2020]{ho2020ddpm}.
</div>

<script>
function getThemeFg() {
	return getComputedStyle(document.documentElement).getPropertyValue('--mn-text').trim() || '#1e293b';
}

const themeFg = getThemeFg();

// =============================================================================
// COLOR NOISE SLIDER (HTML img + range input)
// Pre-computes colored noisy frames as PNG data URLs.
// =============================================================================
const IMG_SIZE = 256; // square resolution used for the slider previews

function loadCleanImage() {
	return new Promise((resolve) => {
		const img = new Image();
		img.crossOrigin = 'anonymous';
		img.onload = () => {
			const canvas = document.createElement('canvas');
			canvas.width = IMG_SIZE;
			canvas.height = IMG_SIZE;
			const ctx = canvas.getContext('2d');
			ctx.drawImage(img, 0, 0, IMG_SIZE, IMG_SIZE);
			resolve(ctx.getImageData(0, 0, IMG_SIZE, IMG_SIZE));
		};
		img.onerror = () => resolve(null);
		img.src = 'diffusion_astronaut.webp';
	});
}

// Mulberry32 seeded PRNG → deterministic noise per frame
function makeRng(seed) {
	let a = seed >>> 0;
	return () => {
		a = (a + 0x6D2B79F5) >>> 0;
		let t = a;
		t = Math.imul(t ^ (t >>> 15), t | 1);
		t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}
function gauss(rng) {
	let u = 0, v = 0;
	while (u === 0) u = rng();
	while (v === 0) v = rng();
	return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

// Build 21 RGB noisy frames and turn each into a base64 PNG data URL.
function buildColorFrames(cleanImageData, numFrames, seedBase) {
	const out = [];
	const W = cleanImageData.width, H = cleanImageData.height;
	const src = cleanImageData.data;
	for (let s = 0; s < numFrames; s++) {
		const t = s / (numFrames - 1);
		const rng = makeRng(seedBase + s * 7919);
		const canvas = document.createElement('canvas');
		canvas.width = W;
		canvas.height = H;
		const ctx = canvas.getContext('2d');
		const img = ctx.createImageData(W, H);
		const dst = img.data;
		const k = Math.sqrt(1 - t);
		const nk = Math.sqrt(t);
		for (let i = 0; i < src.length; i += 4) {
			const r = src[i] / 255;
			const g = src[i + 1] / 255;
			const b = src[i + 2] / 255;
			const nr = k * r + nk * gauss(rng);
			const ng = k * g + nk * gauss(rng);
			const nb = k * b + nk * gauss(rng);
			dst[i]     = Math.max(0, Math.min(255, nr * 255));
			dst[i + 1] = Math.max(0, Math.min(255, ng * 255));
			dst[i + 2] = Math.max(0, Math.min(255, nb * 255));
			dst[i + 3] = 255;
		}
		ctx.putImageData(img, 0, 0);
		out.push({ url: canvas.toDataURL('image/png'), t });
	}
	return out;
}

function mountNoiseSlider(containerId, frames, reverse, titleText) {
	const container = document.getElementById(containerId);
	if (!container) return;
	container.innerHTML =
		'<div style="position:relative;">' +
			'<img id="' + containerId + '-img" style="width:100%; height:auto; display:block; border-radius:6px; background:#1e293b;" />' +
			'<div style="position:absolute; top:8px; left:8px; background:rgba(15,23,42,0.7); color:#fff; padding:4px 10px; border-radius:4px; font-size:12px;">' + titleText + '</div>' +
		'</div>' +
		'<div style="display:flex; align-items:center; gap:12px; margin-top:10px;">' +
			'<input type="range" id="' + containerId + '-range" min="0" max="' + (frames.length - 1) + '" value="' + (reverse ? frames.length - 1 : 0) + '" style="flex:1;" />' +
			'<span id="' + containerId + '-label" style="min-width:120px; font-size:13px; font-variant-numeric:tabular-nums;"></span>' +
		'</div>';
	const img = container.querySelector('img');
	const range = container.querySelector('input[type="range"]');
	const label = container.querySelector('span');

	const order = reverse ? [...frames].reverse() : frames;

	function fmt(t) {
		if (reverse) return 't = ' + (1 - t).toFixed(2) + '  (denoising)';
		if (t === 0) return 't = 0.00  (clean image)';
		if (t === 1) return 't = 1.00  (pure noise)';
		return 't = ' + t.toFixed(2);
	}

	function update(i) {
		img.src = order[i].url;
		label.textContent = fmt(order[i].t);
	}

	range.addEventListener('input', () => update(parseInt(range.value, 10)));
	update(parseInt(range.value, 10));
}


// =============================================================================
// TOKENIZER + EMBEDDING VIZ
// Shows how a CLIP-style tokenizer turns a prompt into subword tokens, and
// each token into a small embedding vector (visualized as a bar chart).
// =============================================================================
function makeTokenizerViz(containerId) {
	const container = document.getElementById(containerId);
	if (!container) return;

	// Illustrative CLIP-style BPE tokenization. Real CLIP uses a different
	// vocabulary; this is a faithful approximation of the structure.
	const prompt = 'a photo of an astronaut riding a horse';
	const tokens = ['a', 'photo', 'of', 'an', 'astro', 'naut', 'riding', 'a', 'horse'];
	const tokenIds = [320, 2844, 539, 550, 22161, 27332, 6792, 320, 4558];

	// Deterministic fake 16-dim embeddings (not real CLIP weights, but
	// structured so similar words get nearby vectors).
	function seed(token) {
		let h = 5381;
		for (let i = 0; i < token.length; i++) h = ((h * 33) + token.charCodeAt(i)) & 0xFFFFFFFF;
		return h;
	}
	function embed(token, dim) {
		const out = new Array(dim);
		let h = seed(token);
		for (let i = 0; i < dim; i++) {
			h = (h * 1103515245 + 12345) & 0x7FFFFFFF;
			out[i] = ((h / 0x7FFFFFFF) - 0.5) * 2;
		}
		return out;
	}
	const dim = 16;
	const embeddings = {};
	for (const t of tokens) embeddings[t] = embed(t, dim);

	const maxBar = 28;

	let html = '<div style="padding:16px 20px; border:1px solid rgba(100,116,139,0.25); border-radius:8px; background:rgba(0,0,0,0.02);">';
	html += '<div style="margin-bottom:10px;"><strong>Step 1 · tokenize</strong> — break the prompt into subword pieces the model has a vector for.</div>';
	html += '<div style="margin-bottom:14px; padding:10px 12px; background:rgba(0,0,0,0.04); border-radius:6px; font-family:Menlo,Consolas,monospace; font-size:14px;">"' + prompt + '"</div>';
	html += '<div style="display:flex; flex-wrap:wrap; gap:6px; margin-bottom:18px;">';
	for (let i = 0; i < tokens.length; i++) {
		const t = tokens[i];
		const subword = i > 0 && tokens[i - 1].length > 1 && !tokens[i - 1].endsWith(' ');
		const color = (subword || t.length <= 2) ? '#64748b' : '#3b82f6';
		html += '<span title="token id ' + tokenIds[i] + '" style="display:inline-block; padding:5px 10px; border-radius:4px; background:' + color + '; color:#fff; font-family:Menlo,Consolas,monospace; font-size:13px;">' + t + '</span>';
	}
	html += '</div>';
	html += '<div style="margin-bottom:10px;"><strong>Step 2 · embed</strong> — each token is mapped to a vector of numbers (here ' + dim + '-dim for display; CLIP uses 768, T5 uses 4096).</div>';
	html += '<div style="display:grid; grid-template-columns:repeat(' + tokens.length + ', 1fr); gap:4px; margin-bottom:14px;">';
	for (const t of tokens) {
		const emb = embeddings[t];
		html += '<div style="display:flex; flex-direction:column; align-items:center;">';
		html += '<div style="font-family:Menlo,Consolas,monospace; font-size:10px; margin-bottom:3px; color:#475569; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; max-width:48px;">' + t + '</div>';
		html += '<div style="display:flex; align-items:center; gap:1px; height:' + (maxBar * 2 + 4) + 'px;">';
		for (let i = 0; i < dim; i++) {
			const v = emb[i];
			const h = Math.max(1, Math.round(Math.abs(v) * maxBar));
			const bg = v >= 0 ? '#3b82f6' : '#ef4444';
			html += '<div title="dim ' + i + ': ' + v.toFixed(2) + '" style="width:6px; height:' + h + 'px; background:' + bg + '; opacity:0.75;"></div>';
		}
		html += '</div></div>';
	}
	html += '</div>';
	html += '<div style="display:flex; gap:14px; align-items:center; font-size:11px; color:#64748b; margin-bottom:10px;">';
	html += '<span><span style="display:inline-block; width:10px; height:10px; background:#3b82f6; vertical-align:middle; margin-right:3px;"></span>positive</span>';
	html += '<span><span style="display:inline-block; width:10px; height:10px; background:#ef4444; vertical-align:middle; margin-right:3px;"></span>negative</span>';
	html += '<span style="margin-left:auto;">bar height = magnitude</span>';
	html += '</div>';
	html += '<div style="font-size:12px; opacity:0.75; line-height:1.5;">Notice that the two "a" tokens get <em>identical</em> vectors, while "horse" and "astro" get completely different ones. This is the same kind of embedding an LLM uses to understand words — see the Embeddings chapter for why these vectors end up capturing meaning.</div>';
	html += '</div>';

	container.innerHTML = html;
}

// =============================================================================
// CROSS-ATTENTION VIZ
// 4×4 image grid + clickable tokens. Clicking a token highlights which
// patches of the image that token "attends to" during denoising.
// Attention maps are synthetic but match the rough layout of a real
// "astronaut riding a horse" image (sky on top, person middle, animal below).
// =============================================================================
function makeCrossAttentionViz(containerId) {
	const container = document.getElementById(containerId);
	if (!container) return;

	const prompt = 'a photo of an astronaut riding a horse';
	const tokens = prompt.split(' ');

	// Regions on the astronaut image (in % of width/height) where each token
	// would attend most strongly. These are simplified illustrations of what a
	// real diffusion model's cross-attention looks like for this prompt.
	const regions = {
		'astronaut': { left: 28, top: 6,  width: 44, height: 38, color: 'rgba(245, 158, 11, 0.45)', label: 'the figure of the astronaut (upper-center, sitting on the horse)' },
		'riding':    { left: 22, top: 32, width: 56, height: 22, color: 'rgba(34, 197, 94, 0.45)',  label: 'the riding action (where astronaut meets horse)' },
		'horse':     { left: 4,  top: 42, width: 92, height: 50, color: 'rgba(239, 68, 68, 0.40)',  label: 'the horse body and legs (most of the lower image)' },
		'photo':     { left: 0,  top: 0,  width: 100, height: 100, color: 'rgba(148, 163, 184, 0.18)', label: 'the whole image (the word "photo" is generic, low attention everywhere)' }
	};

	let html = '<div style="padding:16px 20px; border:1px solid rgba(100,116,139,0.25); border-radius:8px; background:rgba(0,0,0,0.02);">';
	html += '<div style="margin-bottom:6px;"><strong>Prompt:</strong> <span style="font-family:Menlo,Consolas,monospace; font-size:14px;">' + prompt + '</span></div>';
	html += '<div style="margin-bottom:14px; font-size:13px; opacity:0.85;">Click a word to see which part of the image it controls:</div>';
	html += '<div style="margin-bottom:18px; line-height:2;">';
	for (const t of tokens) {
		const has = (t in regions);
		const bg = has ? '#3b82f6' : '#94a3b8';
		const opacity = has ? '1' : '0.5';
		const cursor = has ? 'pointer' : 'default';
		html += '<button data-xatoken="' + t + '" style="margin:2px; padding:5px 12px; border:none; border-radius:4px; background:' + bg + '; color:#fff; cursor:' + cursor + '; font-family:Menlo,Consolas,monospace; font-size:13px; opacity:' + opacity + ';">' + t + '</button> ';
	}
	html += '</div>';
	html += '<div id="' + containerId + '-wrap" style="position:relative; max-width:480px; margin:0 auto; border-radius:6px; overflow:hidden;">';
	html += '<img src="diffusion_astronaut.webp" alt="astronaut riding a horse" style="width:100%; height:auto; display:block;" />';
	html += '<div id="' + containerId + '-overlay" style="position:absolute; top:0; left:0; right:0; bottom:0; pointer-events:none; transition:background 0.25s;"></div>';
	html += '</div>';
	html += '<div id="' + containerId + '-label" style="margin-top:12px; font-size:13px; min-height:1.2em; text-align:center;"><em>Click a content word above to see which region of the image it "claims"</em></div>';
	html += '</div>';

	container.innerHTML = html;

	const overlay = container.querySelector('#' + containerId + '-overlay');
	const label = container.querySelector('#' + containerId + '-label');

	function clearOverlay() {
		overlay.style.background = 'transparent';
		overlay.innerHTML = '';
		label.innerHTML = '<em>Click a content word above to see which region of the image it "claims"</em>';
	}

	container.querySelectorAll('button[data-xatoken]').forEach((btn) => {
		const t = btn.dataset.xatoken;
		if (!(t in regions)) return;
		btn.addEventListener('click', () => {
			const r = regions[t];
			overlay.innerHTML = '<div style="position:absolute; left:' + r.left + '%; top:' + r.top + '%; width:' + r.width + '%; height:' + r.height + '%; background:' + r.color + '; border:2px solid ' + r.color.replace(/0\.\d+\)/, '1)') + '; border-radius:6px; box-sizing:border-box;"></div>';
			label.innerHTML = '<strong>"' + t + '"</strong> controls: ' + r.label;
		});
	});

	// Make "Clear" available by clicking the image again
	container.querySelector('#' + containerId + '-wrap').addEventListener('click', (e) => {
		if (e.target.tagName !== 'IMG') return;
		clearOverlay();
	});
}

// =============================================================================
// BOOT
// =============================================================================
loadCleanImage().then((clean) => {
	if (clean) {
		const forward = buildColorFrames(clean, 21, 12345);
		const reverse = buildColorFrames(clean, 21, 67890);
		mountNoiseSlider('forward-slider', forward, false, 'Forward: clean → noise');
		mountNoiseSlider('reverse-slider', reverse, true, 'Reverse: noise → clean');
	} else {
		['forward-slider', 'reverse-slider'].forEach((id) => {
			const el = document.getElementById(id);
			if (el) el.innerHTML = '<p style="text-align:center;color:#888;">(image failed to load)</p>';
		});
	}
	makeTokenizerViz('tokenizer-viz');
	makeCrossAttentionViz('cross-attention-viz');
});

async function loadDiffusionModule() {
	updateLoadingStatus("Loading section about Diffusion Models...");
	return Promise.resolve();
}
</script>
