<?php include_once("functions.php"); ?>
<!--
COURSE_METADATA:
title: Diffusion Models
description: How Denoising Diffusion Probabilistic Models (DDPM) and Latent Diffusion (Stable Diffusion) generate images by reversing noise.
icon: &#127912;
part: 4
order: 28
color: sky
topics: multimodal, vision, architecture, programming
-->

<div class="image-row md">
	<figure>
		<img src="diffusion_astronaut.webp" alt="An astronaut riding a horse — an image generated by Stable Diffusion 3.5 from the text prompt 'a photograph of an astronaut riding a horse'" />
		<figcaption class="md">A single text prompt, and a diffusion model produced this image in seconds. \cite[Image: Stable Diffusion 3.5]{diffusion_astronaut_img}</figcaption>
	</figure>
</div>

<div class="md">
Most of AI's image generators used to be delicate. GANs collapsed, VAEs blurred, and training them was an art. Then in 2020, a paper called **DDPM** \cite[Ho et al., 2020]{ho2020ddpm} — built on a 2019 idea from Yang Song and Stefano Ermon \cite[Song & Ermon, 2019]{song2019score} — quietly opened a new path. Within two years, Stable Diffusion, DALL·E 2, Imagen, and Midjourney had made **diffusion** the dominant way to generate images. By 2024 it had spread to video (Sora, Veo), audio, music, and even 3D protein structures.

The idea is almost paradoxical: instead of generating an image in one forward pass, **destroy an image with noise step by step, then learn to undo the destruction, one tiny step at a time**. It is a different paradigm from the autoregressive next-token prediction that drives LLMs, even though both produce staggering results.

## The central trick: destroy, then learn to undo

Imagine dropping a clear photograph into a glass of water and slowly stirring in drops of black ink. After each drop the picture becomes a little less recognizable. After enough drops, all you see is uniform grey.

Now imagine the reverse: starting with grey water, learn to *remove* exactly the right amount of ink, drop by drop, until a coherent photograph reappears. If you can learn that reverse process well enough, you can start from *any* grey water and turn it into a fresh, novel photograph.

That is what a diffusion model does. The forward process (ink going in) is a hand-designed procedure with no learned parameters. The reverse process (ink coming out) is what a neural network has to learn.
</div>

<div class="md">
## The forward process: a controlled demolition

Concretely, the forward process takes a clean image $x_0$ and at each of $T$ small timesteps sprinkles in a little Gaussian noise. After $T = 1000$ steps nothing of the original picture survives.

A handy mathematical shortcut is that at any intermediate timestep $t$, you can jump straight from the clean image to $x_t$ in one go, without stepping through all the intermediate $x_1, x_2, \ldots, x_{t-1}$:

$$
x_t \;=\; \sqrt{1-t}\, x_0 \;+\; \sqrt{t}\, \epsilon, \qquad \epsilon \sim \mathcal{N}(0, \mathbf{I})
$$

For $t = 1$ the first term vanishes and $x_T$ is pure Gaussian noise. Crucially, **every step of the forward process is fixed in advance** — no learning required. The forward chain is just a way to manufacture training data for the model that does the hard work.

The slider below shows the forward process happening to a real image. Drag it to watch structure dissolve into pure noise.
</div>

<div id="forward-slider" style="max-width:520px; margin:1em auto;"></div>

<div class="md">
## The reverse process: the part that learns

The reverse process starts from pure noise and runs backward. At each step, the network looks at the current noisy image and asks: *what noise should I subtract to make this slightly more recognizable?* A thousand such tiny denoising steps, and out pops a clean image.

This is the formulation introduced by DDPM. The training objective is almost laughably simple. For a randomly chosen timestep $t$:

1. Take a real image $x_0$.
2. Add the corresponding amount of noise, producing a noisy $x_t$.
3. Ask the network to predict *what that noise was*.
4. Train by mean-squared error between the predicted and the true noise.

That is it. No adversarial game, no careful balancing. Just MSE between predicted and true noise. This stability is one of the big reasons diffusion displaced GANs so quickly.

The slider below steps through the **reverse** process on the same image. Drag it from right to left to watch an image emerge from chaos. In a real diffusion model this would take a thousand tiny denoising steps; here we collapse them into a handful of frames.
</div>

<div id="reverse-slider" style="max-width:520px; margin:1em auto;"></div>

<div class="md">
## Why does this work? The deep reason

You can train a network to denoise without ever asking "denoise *what*?". But the magic is that, by learning to denoise, the network **also learns the shape of the data distribution itself**. This is the deepest "aha" of diffusion, and it has two equivalent ways of seeing it.

**The coarse-to-fine view.** At the very first denoising steps, the image is almost entirely noise — only the largest-scale structure of the data distribution is recoverable. The network first sketches out rough shapes and color fields, and only later refines fine detail. Generation is hierarchical *by construction*: layout first, then texture, then the tiny highlights on a piece of fruit.

**The score-matching view** \cite[Song & Ermon, 2019]{song2019score}. The denoiser is secretly learning the *score function* — the gradient of the log probability density $\nabla_x \log p(x)$, an arrow that tells you which direction in image-space makes the image more "natural". A particle starting from anywhere and following that arrow (with a little noise for randomness, a recipe called **Langevin dynamics**) drifts toward regions where data actually lives, and ends up looking like a sample from the data distribution.

The two views are mathematically equivalent. Denoising *is* learning the score, and learning the score *is* learning to generate.

The plot below shows the score function for a simple 1D "data distribution" that has two peaks (a bimodal distribution, like a mixture of two Gaussians). The blue curve is the density $p(x)$, the red curve is the score $\nabla_x \log p(x)$. Notice that the score **crosses zero exactly at the peaks** — those are the points the data likes to live at — and points outward away from the valleys between peaks. Drag the slider to drop a particle anywhere; it follows the score and ends up at one of the peaks.
</div>

<div id="score-viz" style="max-width:760px; margin:1em auto;"></div>

<div class="md">
## Telling the model what to draw

To make a model draw *what you want*, you have to feed it some signal. For text-to-image, that signal is a text prompt, first encoded into a vector by a separate text encoder (typically CLIP or T5).

The trick that made text-to-image *actually work* is **classifier-free guidance** \cite[Ho & Salimans, 2022]{ho2022cfg}. At training time, the network is shown the text prompt 90% of the time and *nothing* 10% of the time, learning both a conditional and an unconditional denoiser in one model. At inference, you amplify the gap between them:

$$
\tilde\epsilon_\theta(x_t, t, c) \;=\; \epsilon_\theta(x_t, t, \varnothing) \;+\; w \cdot \big(\epsilon_\theta(x_t, t, c) - \epsilon_\theta(x_t, t, \varnothing)\big)
$$

In probability terms, the *output distribution* of the model becomes sharper and shifts toward the prompt as $w$ grows. Below is the same picture in 1D: the broad grey curve is what the unconditional model thinks "an image" looks like, the narrow blue curve is what the conditional model thinks the prompt looks like, and the red curve is what you actually sample from once you scale the gap by $w$. Drag $w$ to see how the output distribution sharpens, shifts, and (for $w > 1$) extrapolates *beyond* the prompt.
</div>

<div id="cfg-viz" style="max-width:760px; margin:1em auto;"></div>

<div class="md">
## Stable Diffusion: doing it in a compressed space

Doing all this in raw pixel space at $512 \times 512$ resolution is brutally expensive. Each image is roughly 786,000 numbers, and the network must process hundreds of millions of them per step.

The breakthrough of **Latent Diffusion Models** \cite[Rombach et al., 2022]{rombach2022ldm} — the technology behind Stable Diffusion — was to *first* compress the image into a much smaller latent representation using a pretrained autoencoder, *then* do all the diffusion work in that compressed space, *then* decode the result back to pixels. The U-Net never sees a pixel; it only sees a $64 \times 64$ latent map. This makes training and inference roughly 64× cheaper.

<figure style="max-width:880px; margin:1.5em auto; text-align:center;">
	<img src="diffusion_architecture.png" alt="Diagram of the Stable Diffusion latent diffusion architecture, showing the text encoder, U-Net denoiser with cross-attention, and VAE encoder/decoder" style="width:100%; height:auto; border-radius:6px;" />
	<figcaption class="md">The Stable Diffusion pipeline: a text encoder turns your prompt into vectors, the U-Net denoises a latent tensor conditioned on those vectors, and a frozen VAE decoder turns the clean latent back into pixels. \cite[Image: Stable Diffusion architecture]{diffusion_architecture_img}</figcaption>
</figure>

The text prompt goes through CLIP, the latent goes through the U-Net, and at the end a frozen VAE decoder turns the clean latent back into an image. The VAE is never trained alongside the diffusion model — it was learned earlier as an ordinary autoencoder and frozen in place.

Below, the famous DDIM denoising sequence for a real Stable Diffusion run shows the same idea in action. Read it from top-left to bottom-right: the network starts from pure noise and gradually reveals a coherent image of a European-style castle in Japan, adding detail with each step.

<figure style="max-width:100%; margin:1.5em auto; text-align:center;">
	<img src="diffusion_ddim_steps.jpg" alt="An X/Y plot of denoising steps showing a European-style castle in Japan becoming progressively more detailed as noise is removed, generated using Stable Diffusion V1-5 with DDIM sampling" style="width:100%; height:auto; border-radius:6px;" />
	<figcaption>Each frame is one denoising step of a Stable Diffusion 1.5 model using DDIM sampling. Early steps establish rough shapes and color fields; later steps refine texture and fine detail. \cite[Image: DDIM denoising steps]{diffusion_ddim_img}</figcaption>
</figure>
</div>

<div class="md">
## Beyond images

The same recipe works anywhere you can define a "noising" process and a network that can reverse it:

* **Video**: Sora, Veo, Stable Video Diffusion — same idea, with an extra time dimension and attention layers that keep frames consistent.
* **Audio**: AudioLDM, DiffSinger — diffuse a spectrogram, then a vocoder turns it back into sound.
* **Music**: Riffusion, MusicLDM.
* **Proteins**: RFdiffusion, Chroma — diffuse over 3D atomic coordinates of new proteins.
* **Robotics**: Diffuser — diffuse over action sequences.
* **Time-series**: TimeGrad — diffuse over weather, financial, or sensor data.

The general principle is almost embarrassingly simple: **if you can blur it, you can unblur it; and if you can unblur it, you can generate it from scratch.**
</div>

<div class="md">
## Where the field is now

By 2025, the diffusion community has largely moved on to **flow matching** \cite[Lipman et al., 2023]{lipman2023flow} — a more general framework where the "noising" path between data and noise can be a straight line instead of a curved one. FLUX, Stable Diffusion 3, and most 2024+ models use it.

The dominant backbone is no longer the U-Net but the **Diffusion Transformer (DiT)** \cite[Peebles & Xie, 2023]{peebles2023dit} — a vanilla Vision Transformer scaled up. Sora, FLUX, and Stable Diffusion 3 all use DiT-style backbones. The pattern is familiar: U-Net worked, then Transformers worked better once they were big enough.

Practical models have also become fast. Modern systems generate images in **1–8 network evaluations** through clever solvers (DPM-Solver, EDM) and adversarial distillation (SDXL-Turbo, LCM). Diffusion is no longer slow.

In five years, the technique went from "diffusion as a curiosity" to "diffusion as the universal generative recipe" for images, video, audio, and molecules.
</div>

<div class="md">
## Try it yourself

These are the tools the diffusion community actually uses:

* **[Stable Diffusion Web UI (AUTOMATIC1111)](https://github.com/AUTOMATIC1111/stable-diffusion-webui){target="_blank" rel="noopener noreferrer"}** — the de facto local frontend. One install, full access to SD 1.5, SDXL, and the entire community of fine-tunes.
* **[ComfyUI](https://github.com/comfyanonymous/ComfyUI){target="_blank" rel="noopener noreferrer"}** — node-based, scriptable, the choice of power users. Best for pipelines that mix ControlNet, LoRA, img2img, inpainting and upscaling.
* **[Fooocus](https://github.com/lllyasviel/Fooocus){target="_blank" rel="noopener noreferrer"}** — minimal UI inspired by Midjourney. Best if you want results without fiddling.
* **[Hugging Face Spaces](https://huggingface.co/spaces){target="_blank" rel="noopener noreferrer"}** — free browser-based demos of the latest open models. No installation, no GPU needed.
* **[InvokeAI](https://github.com/invoke-ai/InvokeAI){target="_blank" rel="noopener noreferrer"}** — a polished commercial-grade CLI and web UI.

For *controlling* what the model draws:

* **[ControlNet](https://github.com/lllyasviel/ControlNet){target="_blank" rel="noopener noreferrer"}** \cite[Zhang et al., 2023]{zhang2023controlnet} — spatial control from edge maps, depth maps, or pose skeletons, without retraining the base model.
* **LoRA** \cite[Hu et al., 2021]{hu2021lora} — small adapters that fine-tune the U-Net's attention layers on a few hundred images of your own style, in minutes on a single GPU. ([paper](https://arxiv.org/abs/2106.09685){target="_blank" rel="noopener noreferrer"})

If you would rather read the foundational papers, the trio that started it all is Sohl-Dickstein's 2015 thermodynamic framing \cite[Sohl-Dickstein et al., 2015]{sohl2015deep}, Song & Ermon's score-based 2019 paper \cite[Song & Ermon, 2019]{song2019score}, and Ho's DDPM in 2020 \cite[Ho et al., 2020]{ho2020ddpm}.
</div>

<script>
function getThemeFg() {
	return getComputedStyle(document.documentElement).getPropertyValue('--mn-text').trim() || '#1e293b';
}

const themeFg = getThemeFg();
const plotlyLayout = (extra) => Object.assign({
	paper_bgcolor: 'rgba(0,0,0,0)',
	plot_bgcolor: 'rgba(0,0,0,0)',
	font: { color: themeFg, size: 12 },
	margin: { t: 50, b: 70, l: 50, r: 20 },
	xaxis: { showgrid: false, zeroline: false, color: themeFg },
	yaxis: { showgrid: false, zeroline: false, color: themeFg }
}, extra || {});

// =============================================================================
// SHARED: Pre-load the astronaut image, downsample to a small grayscale grid
// =============================================================================
const GRID = 48;

function loadCleanGrid() {
	return new Promise((resolve) => {
		const img = new Image();
		img.crossOrigin = 'anonymous';
		img.onload = () => {
			const canvas = document.createElement('canvas');
			canvas.width = GRID;
			canvas.height = GRID;
			const ctx = canvas.getContext('2d');
			ctx.drawImage(img, 0, 0, GRID, GRID);
			const data = ctx.getImageData(0, 0, GRID, GRID).data;
			const grid = new Float32Array(GRID * GRID);
			for (let i = 0; i < GRID * GRID; i++) {
				const r = data[i * 4], g = data[i * 4 + 1], b = data[i * 4 + 2];
				grid[i] = (r + g + b) / (3 * 255);
			}
			resolve(grid);
		};
		img.onerror = () => resolve(null);
		img.src = 'diffusion_astronaut.webp';
	});
}

// Mulberry32 seeded PRNG → deterministic noise per frame
function makeRng(seed) {
	let a = seed >>> 0;
	return () => {
		a = (a + 0x6D2B79F5) >>> 0;
		let t = a;
		t = Math.imul(t ^ (t >>> 15), t | 1);
		t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}
function gauss(rng) {
	let u = 0, v = 0;
	while (u === 0) u = rng();
	while (v === 0) v = rng();
	return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

function buildNoiseFrames(clean, seedBase) {
	const frames = [];
	for (let s = 0; s <= 10; s++) {
		const t = s / 10;
		const rng = makeRng(seedBase + s);
		const z = [];
		for (let y = 0; y < GRID; y++) {
			const row = [];
			for (let x = 0; x < GRID; x++) {
				const idx = y * GRID + x;
				const n = gauss(rng);
				row.push(Math.sqrt(1 - t) * clean[idx] + Math.sqrt(t) * n);
			}
			z.push(row);
		}
		frames.push({ z, t });
	}
	return frames;
}

// =============================================================================
// FORWARD SLIDER — noise 0 → 1 (clean → pure noise)
// =============================================================================
function makeNoiseSlider(containerId, frames, title, reverse) {
	const order = reverse ? [...frames].reverse() : frames;
	const data = [{
		z: order[0].z,
		type: 'heatmap',
		colorscale: 'Greys',
		showscale: false,
		zmin: -1.5,
		zmax: 1.5,
		hovertemplate: ''
	}];

	const plotlyFrames = order.map((f, i) => ({
		name: 'step' + i,
		data: [{ z: f.z }]
	}));

	const sliderSteps = order.map((f, i) => ({
		label: (reverse ? (1 - f.t) : f.t).toFixed(1),
		method: 'animate',
		args: [['step' + i], { mode: 'immediate', transition: { duration: 0 }, frame: { duration: 0, redraw: true } }]
	}));

	const layout = plotlyLayout({
		title: { text: title, font: { size: 13 } },
		sliders: [{
			active: 0,
			currentvalue: {
				prefix: reverse ? 'Denoising step (noise → clean), t = ' : 'Noise level t = ',
				font: { size: 12, color: themeFg },
				xanchor: 'right'
			},
			pad: { t: 30 },
			steps: sliderSteps,
			font: { color: themeFg }
		}],
		xaxis: { showticklabels: false, showgrid: false, zeroline: false, scaleanchor: 'y', constrain: 'domain' },
		yaxis: { showticklabels: false, showgrid: false, zeroline: false },
		margin: { t: 50, b: 80, l: 20, r: 20 }
	});

	Plotly.newPlot(containerId, data, layout, { responsive: true, displayModeBar: false }).then(() => {
		Plotly.addFrames(containerId, plotlyFrames);
	});
}

// =============================================================================
// SCORE-MATCHING VIZ
// 1D bimodal density + score function, plus a draggable particle
// =============================================================================
function makeScoreViz(containerId) {
	const xs = [];
	const dx = 0.02;
	for (let x = -4.5; x <= 4.5; x += dx) xs.push(x);

	const mu1 = -1.6, mu2 = 1.6, sigma = 0.85;
	const gaussPdf = (x, mu) => Math.exp(-0.5 * Math.pow((x - mu) / sigma, 2)) / (sigma * Math.sqrt(2 * Math.PI));
	const p = (x) => 0.5 * gaussPdf(x, mu1) + 0.5 * gaussPdf(x, mu2);
	const dp = (x) => 0.5 * gaussPdf(x, mu1) * (-(x - mu1) / (sigma * sigma))
	             + 0.5 * gaussPdf(x, mu2) * (-(x - mu2) / (sigma * sigma));
	const score = (x) => dp(x) / p(x);

	const pTrace = {
		x: xs, y: xs.map(p), mode: 'lines', name: 'p(x)  data density',
		line: { color: '#3b82f6', width: 2.5 }, yaxis: 'y'
	};
	const sTrace = {
		x: xs, y: xs.map(score), mode: 'lines', name: '∇ₓ log p(x)  score',
		line: { color: '#ef4444', width: 2.5 }, yaxis: 'y2'
	};

	// Arrows on the score subplot: where the score points
	const arrowXs = [];
	for (let x = -4; x <= 4; x += 0.4) arrowXs.push(x);
	const shapes = arrowXs.map((x) => {
		const s = score(x);
		const head = 0.18 * Math.sign(s);
		return {
			type: 'line',
			xref: 'x2', yref: 'y2',
			x0: x, x1: x,
			y0: 0, y1: Math.max(-2.5, Math.min(2.5, s)),
			line: { color: s > 0 ? '#22c55e' : '#a855f7', width: 2 },
			arrowhead: 3, arrowsize: 1, arrowwidth: 1.5
		};
	});

	// Particle: starts at x = -3.5
	let particleX = -3.5;
	const particleTrace = {
		x: [particleX], y: [p(particleX)],
		mode: 'markers+text', name: 'sample x',
		marker: { size: 14, color: '#f59e0b', line: { color: '#92400e', width: 2 } },
		text: ['drag me'], textposition: 'top center',
		textfont: { color: themeFg, size: 11 },
		yaxis: 'y'
	};

	const layout = plotlyLayout({
		grid: { rows: 2, columns: 1, pattern: 'independent' },
		title: { text: 'Score function: arrows point toward where data lives', font: { size: 13 } },
		shapes: shapes,
		xaxis: { title: 'x', range: [-4.5, 4.5] },
		yaxis: { title: 'p(x)', rangemode: 'tozero' },
		xaxis2: { title: 'x', range: [-4.5, 4.5] },
		yaxis2: { title: 'score', range: [-3, 3], zeroline: true, zerolinecolor: themeFg, zerolinewidth: 1 },
		legend: { x: 1.02, y: 1, xanchor: 'left' },
		showlegend: true,
		margin: { t: 50, b: 50, l: 60, r: 140 },
		dragmode: 'pan'
	});

	Plotly.newPlot(containerId, [pTrace, sTrace, particleTrace], layout, { responsive: true, displayModeBar: false }).then((gd) => {
		// Click-to-place or drag the particle
		gd.on('plotly_click', (ev) => {
			if (!ev.points || !ev.points.length) return;
			const pt = ev.points[0];
			if (pt.yaxis !== undefined && pt.yaxis.title && pt.yaxis.title.text && pt.yaxis.title.text.startsWith('p(')) {
				particleX = Math.max(-4.3, Math.min(4.3, pt.x));
				Plotly.restyle(containerId, { x: [[particleX]], y: [[p(particleX)]] }, [2]);
			}
		});

		// "Run Langevin" button: step the particle 200 times along the score
		const btn = document.createElement('button');
		btn.textContent = '▶ Run Langevin dynamics (200 steps)';
		btn.style.cssText = 'margin:8px auto; display:block; padding:8px 16px; background:var(--mn-accent,#3b82f6); color:#fff; border:none; border-radius:6px; cursor:pointer; font:inherit;';
		btn.onclick = async () => {
			btn.disabled = true;
			btn.textContent = 'Following the score…';
			let x = particleX;
			const dt = 0.05;
			const noiseScale = 0.35;
			for (let step = 0; step < 200; step++) {
				const s = score(x);
				x = x + s * dt + noiseScale * Math.sqrt(2 * dt) * gauss(makeRng(step * 991 + 7));
				if (Math.abs(x) > 4.3) x = Math.sign(x) * 4.3;
				particleX = x;
				Plotly.restyle(containerId, { x: [[x]], y: [[p(x)]] }, [2]);
				if (step % 4 === 0) await new Promise(r => setTimeout(r, 12));
			}
			btn.textContent = '↻ Try again from a different starting point';
			btn.disabled = false;
		};
		gd.parentNode.insertBefore(btn, gd.nextSibling);
	});
}

// =============================================================================
// CFG VIZ
// Three 1D distributions + slider for guidance w
// =============================================================================
function makeCfgViz(containerId) {
	const xs = [];
	const dx = 0.02;
	for (let x = -4; x <= 4; x += dx) xs.push(x);

	// Unconditional: broad, centered at 0
	const sigmaU = 1.4;
	const muC = 1.2, sigmaC = 0.45;

	const pu = (x) => Math.exp(-0.5 * Math.pow(x / sigmaU, 2)) / (sigmaU * Math.sqrt(2 * Math.PI));
	const pc = (x) => Math.exp(-0.5 * Math.pow((x - muC) / sigmaC, 2)) / (sigmaC * Math.sqrt(2 * Math.PI));

	// The CFG output distribution for a given w, when both p_u and p_c are Gaussian,
	// is itself Gaussian: log p_cfg ∝ w·log p_c + (1-w)·log p_u (a power-mean)
	const cfgDist = (w) => {
		const vu = sigmaU * sigmaU;
		const vc = sigmaC * sigmaC;
		const vEff = 1 / ((1 - w) / vu + w / vc);
		const mEff = vEff * (w * muC / vc);
		const k = 1 / Math.sqrt(2 * Math.PI * vEff);
		return (x) => k * Math.exp(-0.5 * Math.pow((x - mEff) / Math.sqrt(vEff), 2));
	};

	let w = 7;
	const traceU = {
		x: xs, y: xs.map(pu), mode: 'lines', name: 'p(uncond) — anything goes',
		line: { color: '#94a3b8', width: 2, dash: 'dot' }
	};
	const traceC = {
		x: xs, y: xs.map(pc), mode: 'lines', name: 'p("astronaut on a horse") — the prompt',
		line: { color: '#3b82f6', width: 2.5 }
	};
	const traceCfg = {
		x: xs, y: xs.map(cfgDist(w)), mode: 'lines', name: 'p_cfg — what we actually sample',
		line: { color: '#ef4444', width: 3 },
		fill: 'tozeroy', fillcolor: 'rgba(239,68,68,0.10)'
	};

	const annotation = (w) => ({
		x: 0.5, y: 1.05, xref: 'paper', yref: 'paper',
		text: '<b>guidance scale w = ' + w.toFixed(1) + '</b><br>' +
		      '  output mean μ = ' + (w * muC / (sigmaC * sigmaC) /
		      ((1 - w) / (sigmaU * sigmaU) + w / (sigmaC * sigmaC))).toFixed(2) + ',  ' +
		      'sharpness ↑ as w grows',
		showarrow: false, align: 'center',
		font: { color: themeFg, size: 11 }
	});

	const layout = plotlyLayout({
		title: { text: 'Classifier-free guidance: amplify the gap between unconditional and prompt-conditioned', font: { size: 13 } },
		xaxis: { title: 'image space (one slice)', range: [-4, 4] },
		yaxis: { title: 'probability density' },
		annotations: [annotation(w)],
		legend: { x: 1.02, y: 1, xanchor: 'left', bgcolor: 'rgba(0,0,0,0)' },
		margin: { t: 70, b: 70, l: 60, r: 160 },
		shapes: [{
			type: 'line', x0: muC, x1: muC, y0: 0, y1: pc(muC),
			line: { color: '#3b82f6', width: 1, dash: 'dot' }
		}],
		sliders: [{
			active: 0,
			currentvalue: { prefix: 'Guidance scale w = ', font: { size: 12, color: themeFg }, xanchor: 'right' },
			pad: { t: 30 },
			steps: [0, 1, 2, 3, 5, 7, 10, 15].map((wv) => {
				const label = wv.toString();
				return {
					label: label, method: 'restyle',
					args: [{ y: [xs.map(cfgDist(wv))] }, [2]]
				};
			})
		}]
	});

	// Custom slider event handler to also update annotation
	Plotly.newPlot(containerId, [traceU, traceC, traceCfg], layout, { responsive: true, displayModeBar: false }).then((gd) => {
		gd.on('plotly_sliderchange', (ev) => {
			const wv = parseFloat(ev.step.label);
			Plotly.relayout(containerId, { annotations: [annotation(wv)] });
		});
	});
}

// =============================================================================
// BOOT
// =============================================================================
loadCleanGrid().then((clean) => {
	if (clean) {
		const forwardFrames = buildNoiseFrames(clean, 12345);
		const reverseFrames = buildNoiseFrames(clean, 67890);
		makeNoiseSlider('forward-slider', forwardFrames, 'Forward diffusion: clean image gradually replaced by Gaussian noise', false);
		makeNoiseSlider('reverse-slider', reverseFrames, 'Reverse process: noise gradually resolved into a clean image', true);
	} else {
		['forward-slider', 'reverse-slider'].forEach((id) => {
			document.getElementById(id).innerHTML = '<p style="text-align:center;color:#888;">(image failed to load)</p>';
		});
	}
	makeScoreViz('score-viz');
	makeCfgViz('cfg-viz');
});

async function loadDiffusionModule() {
	updateLoadingStatus("Loading section about Diffusion Models...");
	return Promise.resolve();
}
</script>
