<?php include_once("functions.php"); ?>
<!--
COURSE_METADATA:
title: Diffusion Models
description: How Denoising Diffusion Probabilistic Models (DDPM) and Latent Diffusion (Stable Diffusion) generate images by reversing noise.
icon: &#127912;
part: 4
order: 28
color: sky
topics: multimodal, vision, architecture, programming
-->

<div class="md">
<figure style="margin: 1em 0 1.5em 0;">
	<img style="width: 100%; height: auto; display: block; border-radius: 6px;" src="diffusion_astronaut.webp" alt="An astronaut riding a horse — an image generated by Stable Diffusion 3.5 from the text prompt 'a photograph of an astronaut riding a horse'" />
	<figcaption>A single text prompt, and a diffusion model produced this image in seconds. \cite[Image: Stable Diffusion 3.5]{diffusion_astronaut_img}</figcaption>
</figure>

Most of AI's image generators used to be delicate. GANs collapsed, VAEs blurred, and training them was an art. Then in 2020, a paper called **DDPM** \cite[Ho et al., 2020]{ho2020ddpm} — built on a 2019 idea from Yang Song and Stefano Ermon \cite[Song & Ermon, 2019]{song2019score} — quietly opened a new path. Within two years, Stable Diffusion, DALL·E 2, Imagen, and Midjourney had made **diffusion** the dominant way to generate images. By 2024 it had spread to video (Sora, Veo), audio, music, and even 3D protein structures.

The idea is almost paradoxical: instead of generating an image in one forward pass, **destroy an image with noise step by step, then learn to undo the destruction, one tiny step at a time**. It is a different paradigm from the autoregressive next-token prediction that drives LLMs, even though both produce staggering results.

## The central trick: destroy, then learn to undo

Imagine dropping a clear photograph into a glass of water and slowly stirring in drops of black ink. After each drop the picture becomes a little less recognizable. After enough drops, all you see is uniform grey.

Now imagine the reverse: starting with grey water, learn to *remove* exactly the right amount of ink, drop by drop, until a coherent photograph reappears. If you can learn that reverse process well enough, you can start from *any* grey water and turn it into a fresh, novel photograph.

That is what a diffusion model does. The forward process (ink going in) is a hand-designed procedure with no learned parameters. The reverse process (ink coming out) is what a neural network has to learn.
</div>

<div class="md">
## The forward process: a controlled demolition

Concretely, the forward process takes a clean image $x_0$ and at each of $T$ small timesteps sprinkles in a little Gaussian noise. After $T = 1000$ steps nothing of the original picture survives.

A handy mathematical shortcut is that at any intermediate timestep $t$, you can jump straight from the clean image to $x_t$ in one go, without stepping through all the intermediate $x_1, x_2, \ldots, x_{t-1}$:

$$
x_t \;=\; \sqrt{1-t}\, x_0 \;+\; \sqrt{t}\, \epsilon, \qquad \epsilon \sim \mathcal{N}(0, \mathbf{I})
$$

For $t = 1$ the first term vanishes and $x_T$ is pure Gaussian noise. Crucially, **every step of the forward process is fixed in advance** — no learning required. The forward chain is just a way to manufacture training data for the model that does the hard work.

The slider below shows the forward process happening to a real image. Drag it to watch the picture dissolve into noise.
</div>

<div id="forward-slider" style="max-width: 512px; margin: 1em auto; text-align: center;"></div>

<div class="md">
## The reverse process: the part that learns

The reverse process starts from pure noise and runs backward. At each step, the network looks at the current noisy image and asks: *what noise should I subtract to make this slightly more recognizable?* A thousand such tiny denoising steps, and out pops a clean image.

This is the formulation introduced by DDPM. The training objective is almost laughably simple. For a randomly chosen timestep $t$:

1. Take a real image $x_0$.
2. Add the corresponding amount of noise, producing a noisy $x_t$.
3. Ask the network to predict *what that noise was*.
4. Train by mean-squared error between the predicted and the true noise.

That is it. No adversarial game, no careful balancing. Just MSE between predicted and true noise. This stability is one of the big reasons diffusion displaced GANs so quickly.

The slider below steps through the **reverse** process on the same image. Drag it from right to left to watch an image emerge from chaos. In a real diffusion model this would take a thousand tiny denoising steps; here we collapse them into a handful of frames.
</div>

<div id="reverse-slider" style="max-width: 512px; margin: 1em auto; text-align: center;"></div>

<div class="md">
## Why does this work?

You might ask: how can *removing noise* ever create a picture? The trick is this — **a denoiser that can spot noise must also have learned what "no noise" looks like**. It has implicitly learned the shape of the data distribution. So if you start from pure noise and repeatedly denoise, you trace a path through that distribution, and end up with a brand new sample.

Here is the same idea in 1D. The blue curve is the "data distribution" — it shows where realistic values tend to live (two peaks in this toy example). The arrows on the baseline always point **toward** a peak, away from anywhere that's "not data". Drag the orange dot anywhere on the baseline, then hit the button. The dot follows the arrows into a peak — that is exactly what a denoiser does at every step during generation. Different starting points → different samples.
</div>

<div id="score-viz" style="max-width: 760px; margin: 1em auto;"></div>

<div class="md">
## Telling the model what to draw

To make a model draw *what you want*, you have to feed it some signal. For text-to-image, that signal is a text prompt, first encoded into a vector by a separate text encoder (typically CLIP or T5).

The trick that made text-to-image *actually work* is **classifier-free guidance** \cite[Ho & Salimans, 2022]{ho2022cfg}. At training time, the network is shown the text prompt 90% of the time and *nothing* 10% of the time, learning both a conditional and an unconditional denoiser in one model. At inference, you amplify the gap between them:

$$
\tilde\epsilon_\theta(x_t, t, c) \;=\; \epsilon_\theta(x_t, t, \varnothing) \;+\; w \cdot \big(\epsilon_\theta(x_t, t, c) - \epsilon_\theta(x_t, t, \varnothing)\big)
$$

In probability terms, the *output distribution* of the model becomes sharper and shifts toward the prompt as $w$ grows. Below is the same picture in 1D: the broad grey curve is what the unconditional model thinks "an image" looks like, the narrow blue curve is what the conditional model thinks the prompt looks like, and the red curve is what you actually sample from once you scale the gap by $w$. Drag $w$ to see how the output distribution sharpens, shifts, and (for $w > 1$) extrapolates *beyond* the prompt.
</div>

<div id="cfg-viz" style="max-width: 760px; margin: 1em auto;"></div>

<div class="md">
## Stable Diffusion: doing it in a compressed space

Doing all this in raw pixel space at $512 \times 512$ resolution is brutally expensive. Each image is roughly 786,000 numbers, and the network must process hundreds of millions of them per step.

The breakthrough of **Latent Diffusion Models** \cite[Rombach et al., 2022]{rombach2022ldm} — the technology behind Stable Diffusion — was to *first* compress the image into a much smaller latent representation using a pretrained autoencoder, *then* do all the diffusion work in that compressed space, *then* decode the result back to pixels. The U-Net never sees a pixel; it only sees a $64 \times 64$ latent map. This makes training and inference roughly 64× cheaper.

<figure style="max-width:880px; margin:1.5em auto; text-align:center;">
	<img src="diffusion_architecture.png" alt="Diagram of the Stable Diffusion latent diffusion architecture, showing the text encoder, U-Net denoiser with cross-attention, and VAE encoder/decoder" style="width:100%; height:auto; border-radius:6px;" />
	<figcaption>The Stable Diffusion pipeline: a text encoder turns your prompt into vectors, the U-Net denoises a latent tensor conditioned on those vectors, and a frozen VAE decoder turns the clean latent back into pixels. \cite[Image: Stable Diffusion architecture]{diffusion_architecture_img}</figcaption>
</figure>

The text prompt goes through CLIP, the latent goes through the U-Net, and at the end a frozen VAE decoder turns the clean latent back into an image. The VAE is never trained alongside the diffusion model — it was learned earlier as an ordinary autoencoder and frozen in place.

Below, the famous DDIM denoising sequence for a real Stable Diffusion run shows the same idea in action. Read it from top-left to bottom-right: the network starts from pure noise and gradually reveals a coherent image of a European-style castle in Japan, adding detail with each step.

<figure style="max-width:100%; margin:1.5em auto; text-align:center;">
	<img src="diffusion_ddim_steps.jpg" alt="An X/Y plot of denoising steps showing a European-style castle in Japan becoming progressively more detailed as noise is removed, generated using Stable Diffusion V1-5 with DDIM sampling" style="width:100%; height:auto; border-radius:6px;" />
	<figcaption>Each frame is one denoising step of a Stable Diffusion 1.5 model using DDIM sampling. Early steps establish rough shapes and color fields; later steps refine texture and fine detail. \cite[Image: DDIM denoising steps]{diffusion_ddim_img}</figcaption>
</figure>
</div>

<div class="md">
## Beyond images

The same recipe works anywhere you can define a "noising" process and a network that can reverse it:

* **Video**: Sora, Veo, Stable Video Diffusion — same idea, with an extra time dimension and attention layers that keep frames consistent.
* **Audio**: AudioLDM, DiffSinger — diffuse a spectrogram, then a vocoder turns it back into sound.
* **Music**: Riffusion, MusicLDM.
* **Proteins**: RFdiffusion, Chroma — diffuse over 3D atomic coordinates of new proteins.
* **Robotics**: Diffuser — diffuse over action sequences.
* **Time-series**: TimeGrad — diffuse over weather, financial, or sensor data.

The general principle is almost embarrassingly simple: **if you can blur it, you can unblur it; and if you can unblur it, you can generate it from scratch.**
</div>

<div class="md">
## Where the field is now

By 2025, the diffusion community has largely moved on to **flow matching** \cite[Lipman et al., 2023]{lipman2023flow} — a more general framework where the "noising" path between data and noise can be a straight line instead of a curved one. FLUX, Stable Diffusion 3, and most 2024+ models use it.

The dominant backbone is no longer the U-Net but the **Diffusion Transformer (DiT)** \cite[Peebles & Xie, 2023]{peebles2023dit} — a vanilla Vision Transformer scaled up. Sora, FLUX, and Stable Diffusion 3 all use DiT-style backbones. The pattern is familiar: U-Net worked, then Transformers worked better once they were big enough.

Practical models have also become fast. Modern systems generate images in **1–8 network evaluations** through clever solvers (DPM-Solver, EDM) and adversarial distillation (SDXL-Turbo, LCM). Diffusion is no longer slow.

In five years, the technique went from "diffusion as a curiosity" to "diffusion as the universal generative recipe" for images, video, audio, and molecules.
</div>

<div class="md">
## Try it yourself

These are the tools the diffusion community actually uses:

* **[Stable Diffusion Web UI (AUTOMATIC1111)](https://github.com/AUTOMATIC1111/stable-diffusion-webui)** — the de facto local frontend. One install, full access to SD 1.5, SDXL, and the entire community of fine-tunes.
* **[ComfyUI](https://github.com/comfyanonymous/ComfyUI)** — node-based, scriptable, the choice of power users. Best for pipelines that mix ControlNet, LoRA, img2img, inpainting and upscaling.
* **[Fooocus](https://github.com/lllyasviel/Fooocus)** — minimal UI inspired by Midjourney. Best if you want results without fiddling.
* **[Hugging Face Spaces](https://huggingface.co/spaces)** — free browser-based demos of the latest open models. No installation, no GPU needed.
* **[InvokeAI](https://github.com/invoke-ai/InvokeAI)** — a polished commercial-grade CLI and web UI.

For *controlling* what the model draws:

* **[ControlNet](https://github.com/lllyasviel/ControlNet)** \cite[Zhang et al., 2023]{zhang2023controlnet} — spatial control from edge maps, depth maps, or pose skeletons, without retraining the base model.
* **LoRA** \cite[Hu et al., 2021]{hu2021lora} — small adapters that fine-tune the U-Net's attention layers on a few hundred images of your own style, in minutes on a single GPU. ([paper](https://arxiv.org/abs/2106.09685))

If you would rather read the foundational papers, the trio that started it all is Sohl-Dickstein's 2015 thermodynamic framing \cite[Sohl-Dickstein et al., 2015]{sohl2015deep}, Song & Ermon's score-based 2019 paper \cite[Song & Ermon, 2019]{song2019score}, and Ho's DDPM in 2020 \cite[Ho et al., 2020]{ho2020ddpm}.
</div>

<script>
function getThemeFg() {
	return getComputedStyle(document.documentElement).getPropertyValue('--mn-text').trim() || '#1e293b';
}

const themeFg = getThemeFg();

// =============================================================================
// COLOR NOISE SLIDER (HTML img + range input)
// Pre-computes colored noisy frames as PNG data URLs.
// =============================================================================
const IMG_SIZE = 256; // square resolution used for the slider previews

function loadCleanImage() {
	return new Promise((resolve) => {
		const img = new Image();
		img.crossOrigin = 'anonymous';
		img.onload = () => {
			const canvas = document.createElement('canvas');
			canvas.width = IMG_SIZE;
			canvas.height = IMG_SIZE;
			const ctx = canvas.getContext('2d');
			ctx.drawImage(img, 0, 0, IMG_SIZE, IMG_SIZE);
			resolve(ctx.getImageData(0, 0, IMG_SIZE, IMG_SIZE));
		};
		img.onerror = () => resolve(null);
		img.src = 'diffusion_astronaut.webp';
	});
}

// Mulberry32 seeded PRNG → deterministic noise per frame
function makeRng(seed) {
	let a = seed >>> 0;
	return () => {
		a = (a + 0x6D2B79F5) >>> 0;
		let t = a;
		t = Math.imul(t ^ (t >>> 15), t | 1);
		t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}
function gauss(rng) {
	let u = 0, v = 0;
	while (u === 0) u = rng();
	while (v === 0) v = rng();
	return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

// Build 21 RGB noisy frames and turn each into a base64 PNG data URL.
function buildColorFrames(cleanImageData, numFrames, seedBase) {
	const out = [];
	const W = cleanImageData.width, H = cleanImageData.height;
	const src = cleanImageData.data;
	for (let s = 0; s < numFrames; s++) {
		const t = s / (numFrames - 1);
		const rng = makeRng(seedBase + s * 7919);
		const canvas = document.createElement('canvas');
		canvas.width = W;
		canvas.height = H;
		const ctx = canvas.getContext('2d');
		const img = ctx.createImageData(W, H);
		const dst = img.data;
		const k = Math.sqrt(1 - t);
		const nk = Math.sqrt(t);
		for (let i = 0; i < src.length; i += 4) {
			const r = src[i] / 255;
			const g = src[i + 1] / 255;
			const b = src[i + 2] / 255;
			const nr = k * r + nk * gauss(rng);
			const ng = k * g + nk * gauss(rng);
			const nb = k * b + nk * gauss(rng);
			dst[i]     = Math.max(0, Math.min(255, nr * 255));
			dst[i + 1] = Math.max(0, Math.min(255, ng * 255));
			dst[i + 2] = Math.max(0, Math.min(255, nb * 255));
			dst[i + 3] = 255;
		}
		ctx.putImageData(img, 0, 0);
		out.push({ url: canvas.toDataURL('image/png'), t });
	}
	return out;
}

function mountNoiseSlider(containerId, frames, reverse, titleText) {
	const container = document.getElementById(containerId);
	if (!container) return;
	container.innerHTML =
		'<div style="position:relative;">' +
			'<img id="' + containerId + '-img" style="width:100%; height:auto; display:block; border-radius:6px; background:#1e293b;" />' +
			'<div style="position:absolute; top:8px; left:8px; background:rgba(15,23,42,0.7); color:#fff; padding:4px 10px; border-radius:4px; font-size:12px;">' + titleText + '</div>' +
		'</div>' +
		'<div style="display:flex; align-items:center; gap:12px; margin-top:10px;">' +
			'<input type="range" id="' + containerId + '-range" min="0" max="' + (frames.length - 1) + '" value="' + (reverse ? frames.length - 1 : 0) + '" style="flex:1;" />' +
			'<span id="' + containerId + '-label" style="min-width:120px; font-size:13px; font-variant-numeric:tabular-nums;"></span>' +
		'</div>';
	const img = container.querySelector('img');
	const range = container.querySelector('input[type="range"]');
	const label = container.querySelector('span');

	const order = reverse ? [...frames].reverse() : frames;

	function fmt(t) {
		if (reverse) return 't = ' + (1 - t).toFixed(2) + '  (denoising)';
		if (t === 0) return 't = 0.00  (clean image)';
		if (t === 1) return 't = 1.00  (pure noise)';
		return 't = ' + t.toFixed(2);
	}

	function update(i) {
		img.src = order[i].url;
		label.textContent = fmt(order[i].t);
	}

	range.addEventListener('input', () => update(parseInt(range.value, 10)));
	update(parseInt(range.value, 10));
}

// =============================================================================
// SIMPLE "WHY DIFFUSION WORKS" VIZ
// One panel: density curve + arrows pointing inward + draggable orange dot
// that, on the "Denoise!" button, follows the arrows into a peak.
// =============================================================================
function makeSimpleScoreViz(containerId) {
	const xs = [];
	for (let x = -5; x <= 5; x += 0.02) xs.push(x);

	const mu1 = -2, mu2 = 2, sigma = 0.9;
	const density = (x) => {
		const a = Math.exp(-0.5 * Math.pow((x - mu1) / sigma, 2));
		const b = Math.exp(-0.5 * Math.pow((x - mu2) / sigma, 2));
		return 0.5 * (a + b) / (sigma * Math.sqrt(2 * Math.PI));
	};
	const score = (x) => {
		const p1 = Math.exp(-0.5 * Math.pow((x - mu1) / sigma, 2));
		const p2 = Math.exp(-0.5 * Math.pow((x - mu2) / sigma, 2));
		const p = 0.5 * (p1 + p2);
		if (p < 1e-12) return 0;
		const dp = 0.5 * (p1 * (-(x - mu1) / (sigma * sigma)) + p2 * (-(x - mu2) / (sigma * sigma)));
		return Math.max(-2.5, Math.min(2.5, dp / p));
	};

	const densityTrace = {
		x: xs, y: xs.map(density), mode: 'lines', name: 'data distribution',
		line: { color: '#3b82f6', width: 3 },
		fill: 'tozeroy', fillcolor: 'rgba(59, 130, 246, 0.18)'
	};

	// Arrows at sampled x positions. We scale the score so the longest arrow
	// fits inside the visible plot (~0.35 in y-units), and use green for arrows
	// that point toward a peak on the right, purple for arrows that point left.
	const arrowXs = [];
	for (let x = -4.5; x <= 4.5; x += 0.5) arrowXs.push(x);
	const arrowScale = 0.18;
	const arrowCap = 0.35;
	const shapes = arrowXs.map((x) => {
		const s = score(x);
		const len = Math.min(Math.abs(s) * arrowScale, arrowCap);
		if (s > 0) {
			return {
				type: 'line',
				x0: x, x1: x + len, y0: 0, y1: 0,
				line: { color: '#16a34a', width: 2.5 },
				arrowhead: 3, arrowsize: 1.2, arrowwidth: 2
			};
		} else if (s < 0) {
			return {
				type: 'line',
				x0: x, x1: x - len, y0: 0, y1: 0,
				line: { color: '#a855f7', width: 2.5 },
				arrowhead: 3, arrowsize: 1.2, arrowwidth: 2
			};
		}
		return null;
	}).filter(Boolean);

	let particleX = -4.6;
	const particleTrace = {
		x: [particleX], y: [density(particleX)],
		mode: 'markers+text', name: 'noisy sample',
		marker: { size: 16, color: '#f59e0b', line: { color: '#92400e', width: 2 } },
		text: ['drag me →'], textposition: 'middle right',
		textfont: { color: themeFg, size: 11 },
		showlegend: false
	};

	const layout = {
		title: { text: 'The denoiser learns an arrow that always points toward real data', font: { size: 13 } },
		xaxis: { title: 'image space (one slice)', range: [-5, 5], zeroline: false },
		yaxis: { title: 'how often data lives here', range: [0, 0.45], zeroline: false },
		shapes: shapes,
		showlegend: false,
		margin: { t: 60, b: 50, l: 60, r: 30 },
		paper_bgcolor: 'rgba(0,0,0,0)',
		plot_bgcolor: 'rgba(0,0,0,0)',
		font: { color: themeFg, size: 12 },
		annotations: [{
			x: 0.99, y: 0.98, xref: 'paper', yref: 'paper',
			text: '→ green = arrow points toward the left peak<br>' +
			      '← purple = arrow points toward the right peak',
			showarrow: false, align: 'right',
			font: { color: themeFg, size: 10 },
			bgcolor: 'rgba(255,255,255,0.0)'
		}]
	};

	Plotly.newPlot(containerId, [densityTrace, particleTrace], layout, { responsive: true, displayModeBar: false }).then((gd) => {
		gd.on('plotly_click', (ev) => {
			if (!ev.points || !ev.points.length) return;
			const pt = ev.points[0];
			if (pt.curveNumber !== 0) return;
			particleX = Math.max(-4.8, Math.min(4.8, pt.x));
			Plotly.restyle(containerId, { x: [[particleX]], y: [[density(particleX)]] }, [1]);
		});

		const btn = document.createElement('button');
		btn.textContent = '▶ Denoise: follow the arrows (300 steps)';
		btn.style.cssText = 'margin:12px auto; display:block; padding:10px 18px; background:var(--mn-accent,#3b82f6); color:#fff; border:none; border-radius:6px; cursor:pointer; font:inherit;';
		btn.onclick = async () => {
			btn.disabled = true;
			btn.textContent = 'Following the arrows…';
			let x = particleX;
			const dt = 0.05;
			const noiseScale = 0.35;
			for (let step = 0; step < 300; step++) {
				const s = score(x);
				x = x + s * dt + noiseScale * Math.sqrt(2 * dt) * gauss(makeRng(step * 991 + 7));
				if (Math.abs(x) > 4.8) x = Math.sign(x) * 4.8;
				particleX = x;
				Plotly.restyle(containerId, { x: [[x]], y: [[density(x)]] }, [1]);
				if (step % 5 === 0) await new Promise(r => setTimeout(r, 10));
			}
			btn.textContent = '↻ Try again from a different starting point';
			btn.disabled = false;
		};
		gd.parentNode.insertBefore(btn, gd.nextSibling);
	});
}

// =============================================================================
// CFG VIZ — three distributions + slider for guidance w
// =============================================================================
function makeCfgViz(containerId) {
	const xs = [];
	for (let x = -4; x <= 4; x += 0.02) xs.push(x);

	const sigmaU = 1.4;
	const muC = 1.2, sigmaC = 0.45;
	const pu = (x) => Math.exp(-0.5 * Math.pow(x / sigmaU, 2)) / (sigmaU * Math.sqrt(2 * Math.PI));
	const pc = (x) => Math.exp(-0.5 * Math.pow((x - muC) / sigmaC, 2)) / (sigmaC * Math.sqrt(2 * Math.PI));
	const cfgDist = (w) => {
		const vu = sigmaU * sigmaU, vc = sigmaC * sigmaC;
		const vEff = 1 / ((1 - w) / vu + w / vc);
		const mEff = vEff * (w * muC / vc);
		const k = 1 / Math.sqrt(2 * Math.PI * vEff);
		return (x) => k * Math.exp(-0.5 * Math.pow((x - mEff) / Math.sqrt(vEff), 2));
	};

	const traceU = {
		x: xs, y: xs.map(pu), mode: 'lines', name: 'p(uncond) — "anything goes"',
		line: { color: '#94a3b8', width: 2, dash: 'dot' }
	};
	const traceC = {
		x: xs, y: xs.map(pc), mode: 'lines', name: 'p("astronaut on a horse") — the prompt',
		line: { color: '#3b82f6', width: 2.5 }
	};
	const initialW = 7;
	const traceCfg = {
		x: xs, y: xs.map(cfgDist(initialW)), mode: 'lines', name: 'p_cfg — what we actually sample',
		line: { color: '#ef4444', width: 3 },
		fill: 'tozeroy', fillcolor: 'rgba(239, 68, 68, 0.10)'
	};

	const annotation = (w) => ({
		x: 0.5, y: 1.05, xref: 'paper', yref: 'paper',
		text: '<b>guidance scale w = ' + w.toFixed(1) + '</b> &nbsp;·&nbsp; ' +
		      'output mean μ = ' + (w * muC / (sigmaC * sigmaC) /
		      ((1 - w) / (sigmaU * sigmaU) + w / (sigmaC * sigmaC))).toFixed(2) +
		      ' &nbsp;·&nbsp; sharpness ↑ as w grows',
		showarrow: false, align: 'center',
		font: { color: themeFg, size: 11 }
	});

	const layout = {
		title: { text: 'Classifier-free guidance: amplify the gap between unconditional and prompt-conditioned', font: { size: 13 } },
		xaxis: { title: 'image space (one slice)', range: [-4, 4], zeroline: false },
		yaxis: { title: 'probability density', zeroline: false },
		annotations: [annotation(initialW)],
		legend: { x: 1.02, y: 1, xanchor: 'left', bgcolor: 'rgba(0,0,0,0)' },
		margin: { t: 70, b: 70, l: 60, r: 160 },
		shapes: [{
			type: 'line', x0: muC, x1: muC, y0: 0, y1: pc(muC),
			line: { color: '#3b82f6', width: 1, dash: 'dot' }
		}],
		sliders: [{
			active: 0,
			currentvalue: { prefix: 'Guidance scale w = ', font: { size: 12, color: themeFg }, xanchor: 'right' },
			pad: { t: 30 },
			steps: [0, 1, 2, 3, 5, 7, 10, 15].map((wv) => ({
				label: wv.toString(), method: 'restyle',
				args: [{ y: [xs.map(cfgDist(wv))] }, [2]]
			}))
		}],
		paper_bgcolor: 'rgba(0,0,0,0)',
		plot_bgcolor: 'rgba(0,0,0,0)',
		font: { color: themeFg, size: 12 }
	};

	Plotly.newPlot(containerId, [traceU, traceC, traceCfg], layout, { responsive: true, displayModeBar: false }).then((gd) => {
		gd.on('plotly_sliderchange', (ev) => {
			const wv = parseFloat(ev.step.label);
			Plotly.relayout(containerId, { annotations: [annotation(wv)] });
		});
	});
}

// =============================================================================
// BOOT
// =============================================================================
loadCleanImage().then((clean) => {
	if (clean) {
		const forward = buildColorFrames(clean, 21, 12345);
		const reverse = buildColorFrames(clean, 21, 67890);
		mountNoiseSlider('forward-slider', forward, false, 'Forward: clean → noise');
		mountNoiseSlider('reverse-slider', reverse, true, 'Reverse: noise → clean');
	} else {
		['forward-slider', 'reverse-slider'].forEach((id) => {
			const el = document.getElementById(id);
			if (el) el.innerHTML = '<p style="text-align:center;color:#888;">(image failed to load)</p>';
		});
	}
	makeSimpleScoreViz('score-viz');
	makeCfgViz('cfg-viz');
});

async function loadDiffusionModule() {
	updateLoadingStatus("Loading section about Diffusion Models...");
	return Promise.resolve();
}
</script>
