<?php include_once("functions.php"); ?>

<div class="md">
Modern LLMs are often seen as a 21st-century invention, but their conceptual DNA reaches back over two millennia to when humans first tried to treat language as a formal machine.

## 1. Pāṇini and the First "Compiler" (c. 4th Century BCE)
Long before the first computer, the Indian grammarian **Pāṇini** wrote the *Aṣṭādhyāyī*. He developed 3,959 rules (sutras) that defined the entire structure of Sanskrit.
* **The Deep Link:** Pāṇini did not just describe language; he created a **generative formal system**. His rules functioned like a modern programming language or a context-free grammar. This was the first proof that the "infinite" complexity of human speech could be generated by a "finite" set of mathematical rules—the exact premise of any generative AI.

## 2. Ramon Llull and the "Thinking Machine" (1232–1315)
The user mentioned **Ramon Llull**, and his inclusion is vital. In his *Ars Magna*, Llull built a system of rotating paper disks (the *Volvelles*) inscribed with concepts. By turning the wheels, he believed one could generate all possible truths through **combinatorics**.
* **The Deep Link:** Llull pioneered **"Calculus ratiocinator"**—the idea that reasoning is just a form of computation. He was the first to attempt "automated reasoning" by combining symbols. While his "database" was religious, his *process*—mapping concepts to a physical mechanism to generate new ideas—is the direct mechanical ancestor of the **Self-Attention** mechanism.

## 3. Leibniz and the "Universal Characteristic" (17th Century)
Inspired by Llull, **Gottfried Wilhelm Leibniz** dreamed of a *Characteristica Universalis*—a universal language where every concept was assigned a unique number.
* **The Deep Link:** This is the earliest vision of **Word Embeddings**. Leibniz believed we could resolve any philosophical argument by saying *"Calculemus"* (Let us calculate). He wanted to turn language into a vector space where "meaning" was just the result of arithmetic.

## 4. The Bridge to Modernity: Structuralism and Firth
In the 20th century, the focus shifted from "God's logic" to "Statistical logic":
* **Ferdinand de Saussure (1916):** He argued that words have no "soul," only **relational value**. A word is defined by what it is *not*. This "Differential" view is why we can map words as distances in a high-dimensional manifold today.
* **J.R. Firth (1957):** His **Distributional Hypothesis**—*"You shall know a word by the company it keeps"*—is the single most important linguistic rule for LLMs. It moved us away from hand-coded "Pāṇinian" rules and toward the idea that if a model sees enough text, it will "absorb" the rules of reality through the statistical patterns of how words neighbor each other.

## 5. The Final Inversion: The "Bitter Lesson"
The history of AI ended a decades-long war between the **"Rule-Builders"** (who followed Pāṇini and Chomsky) and the **"Connectionists"** (who followed the statistical path of Shannon and Firth). 
* **The Result:** As described in **Rich Sutton’s "The Bitter Lesson,"** we learned that human-designed linguistic heuristics (like trying to teach an AI what a "noun" is) eventually hit a ceiling. The "Deep" history ends with the realization that the best way to "understand" language is not to define it, but to provide a massive architecture (like the Transformer) and let the machine discover its own "hidden harmony" through raw computation.
</div>
