#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"

bash find_double_defined_js.sh

python3 -m py_compile py/**/*.py

python3 py/qos.py py
