<?php include_once("functions.php"); ?>
<!--
COURSE_METADATA:
title: Unexpected Capabilities of LLMs
description: Discoveries that surprised researchers — emergent abilities, reasoning, theory of mind, self-improvement, and the strange things LLMs can do that nobody trained them for.
icon: &#10024;
part: 6
order: 45
color: text-secondary
topics: emergence, reasoning, interpretability, philosophy
-->

<div class="md">
LLMs were trained on a single, well-defined objective: **next-token prediction**. The architecture is a stack of attention layers, the data is text. Everything else — reasoning, world-modelling, theory of mind, tool use — was not specified, not rewarded, and in many cases not even expected to be possible. Yet, capability after capability kept *emerging* during scaling. The list below catalogues the most striking of these discoveries, each with a citation to the paper that first reported it and a short note on *why* it was unexpected.

### Few-Shot In-Context Learning (GPT-3, 2020)

The first major surprise. \cite[Brown et al., 2020]{brown2020gpt3} showed that a 175-billion parameter autoregressive language model could be conditioned on a handful of input-output examples written into the prompt and then continue the pattern on a new query — **without any weight updates, without gradient descent, without a fine-tuning loop**. This was not how language modelling was supposed to work. Prior to GPT-3, neural NLP required task-specific architectures, features, and training. After GPT-3, "prompting" became a programming interface. The deeper surprise was that the ability appeared *smoothly* with scale: at small scales models ignore the examples, at large scales they exploit them reliably.

### In-Context Statistical Learning

In 2022, \cite[Garg, Tsipras, Liang & Valiant, 2022]{garg2022incontext} asked a sharper question: if a Transformer is trained on sequences drawn from a *family* of functions (e.g. linear functions $f(x) = w^\top x$ with random $w$), can it in-context learn a *new* function from that family on the fly? The answer was yes: at test time, given a few noisy $(x, y)$ pairs, the model produced predictions matching the **optimal least-squares estimator** for that function class, *without ever performing gradient descent at inference*. The result extended to sparse linear functions, two-layer neural networks, and decision trees, in each case matching or exceeding specialised task-specific learning algorithms. This established that in-context learning is not task recognition (looking up a similar pretraining task) but genuine inference-time algorithm execution.

### Induction Heads: The Circuit Behind ICL

If in-context learning is real inference, it must be implemented in some specific circuitry. \cite[Olsson et al., 2022]{olsson2022induction} identified **induction heads** — pairs of attention heads that implement the simple algorithm "complete $[A][B]\dots[A] \to [B]$". Across six complementary lines of evidence, they showed that induction heads develop at *precisely the same training step* as a sudden jump in in-context learning ability (visible as a discontinuity in the loss curve). The implication: many "emergent" capabilities of LLMs may be the macroscopic signature of a small, identifiable circuit forming inside the network. This is now one of the cleanest examples of *mechanistic interpretability* — explaining a behaviour by finding the responsible weights.

### Chain-of-Thought Reasoning Emerges From a Prompt

In January 2022, \cite[Wei et al., 2022]{wei2022chainofthought} demonstrated that appending *"Let's think step by step"* (or showing worked examples) to a prompt dramatically improves a model's performance on arithmetic, commonsense, and symbolic reasoning benchmarks — sometimes by **more than 50 percentage points**. \cite[Kojima et al., 2022]{kojima2022zeroshot} then showed the same effect *without any worked examples*, using only the magic suffix. Before this work, the standard assumption was that a frozen language model performs a fixed amount of "reasoning" per forward pass. Chain-of-Thought revealed that the model already contained latent multi-step reasoning capability — it merely needed permission (in the form of the right prompt) to surface it. This finding directly enabled the entire modern reasoning paradigm culminating in o1, o3, and DeepSeek-R1.

### Self-Consistency and Tree of Thoughts

Once reasoning can be sampled, two natural refinements appeared. \cite[Wang et al., 2022]{wang2022selfconsistency} showed that sampling *many* chain-of-thought traces and taking the majority answer outperforms greedy decoding, on the intuition that correct reasoning paths converge while incorrect ones diverge. \cite[Yao et al., 2023]{yao2023tot} pushed this further with **Tree of Thoughts**: the model generates multiple candidate next steps, *evaluates* each, and decides whether to continue, branch, or backtrack. On the Game of 24 (a combinatorial puzzle), chain-of-thought GPT-4 solved 4% of problems; Tree of Thoughts solved 74%. The surprise was not that the model could reason, but that the same model could be coaxed into *deliberate* search and self-evaluation by changes to the inference loop alone.

### Algorithmic Prompting

What happens if you give an LLM the *algorithm* for a task instead of examples? \cite[Zhou et al., 2022]{zhou2022algorithmic} tested this on 19-digit addition: a plain few-shot baseline reached 9.5% accuracy; an in-context description of the addition algorithm reached **90.5%**. The model was not memorising the answers (the numbers were random), not retrieving the algorithm from pretraining (it was given verbatim in the prompt), and not gradient-descenting on the task. It was *executing* an algorithm it had never seen before, by reading the algorithm from natural-language instructions. This is a strong empirical anchor for the claim that LLMs can perform general algorithmic computation when the procedure is specified unambiguously.

### Emergent World Representations — Othello-GPT

Perhaps the most surprising mechanistic finding of 2022. \cite[Li et al., 2022][]{li2022othello_iclr} trained a small GPT on **move sequences from the board game Othello** — the model never saw the board, only the sequence of moves. Probing the internal activations, they found a non-linear representation of the full board state had spontaneously formed inside the network: each cell's "colour" (black, white, empty) could be linearly decoded from specific neurons. Causal interventions (artificially flipping a cell's representation) caused the model to predict legal moves as if the board had actually been flipped. The model had invented a world model because predicting the next move required it. The lesson: a sufficiently expressive next-token predictor, trained on a sufficiently structured sequence, builds internal representations of the underlying generative process whether or not we ask it to.

### Theory of Mind

Theory of Mind — the ability to model that other agents hold beliefs that may differ from reality — was long considered a uniquely human cognitive capacity, emerging around age four. \cite[Kosinski, 2024][]{kosinski2023tom} tested 11 LLMs on 40 False-Belief scenarios (640 prompts in total). The result was striking: smaller and older models solved 0% of tasks; GPT-3-davinci-003 (Nov 2022) solved 20%; ChatGPT-3.5 (Mar 2023) solved 20%; **ChatGPT-4 (Jun 2023) solved 75%**, statistically indistinguishable from six-year-old children. ToM was not in the training objective; it was not reinforced; it was not a benchmark anyone was optimising for. It *emerged spontaneously* as a side-effect of language modelling scaling. The result is contested in detail (subsequent papers find that small prompt perturbations break the ability), but the central finding — that frontier models display systematic ToM behaviour on standard tests — is robust.

### Self-Taught Tool Use — Toolformer

Language models famously struggle with exact arithmetic and factual lookup. \cite[Schick et al., 2023][]{schick2023toolformer} showed that a model can teach *itself* to call external APIs (a calculator, a search engine, a translation system, a calendar) by a self-supervised procedure: write candidate API calls into text, execute them, keep the calls that *reduce the loss* on subsequent tokens, discard the rest. The resulting model — **Toolformer** — substantially improved zero-shot performance on a variety of downstream tasks, often matching much larger models. The surprise was twofold: (a) the supervision signal (loss reduction) was extremely weak, yet sufficient to teach tool use from raw text; (b) the model learned *which* tool to call, *when*, *with what arguments*, and *how to incorporate the result*, all without human-labelled tool-use examples.

### Sparks of AGI (GPT-4)

In March 2023, a team at Microsoft Research published a 154-page investigation of an early GPT-4 checkpoint titled \textit{Sparks of Artificial General Intelligence} \cite[Bubeck et al., 2023][]{bubeck2023sparks}. Their central claim was that GPT-4, beyond its mastery of language, could solve novel and difficult tasks spanning mathematics, coding, vision, medicine, law, and psychology — *without needing any special prompting* — and that its performance was "strikingly close to human-level performance" in many of these domains. The paper documented abilities the authors had not anticipated: synthesising novel proofs, writing functioning code from a one-line description, explaining jokes, drawing ASCII art on request, and passing professional exams (bar exam, medical board) in the 90th percentile or above. Whether or not one accepts the "AGI" framing, the paper is a careful catalogue of capabilities that nobody — including OpenAI — predicted when scaling GPT-3.

### Spontaneous Coding Ability — Codex & HumanEval

For decades, code generation was treated as its own sub-field with its own architectures (abstract syntax trees, program induction, neuro-symbolic systems). Then \cite[Chen et al., 2021][]{chen2021humaneval} fine-tuned a 12-billion-parameter GPT on GitHub code and produced **Codex**. On HumanEval — a benchmark of 164 hand-written Python problems — Codex solved 28.8% of problems in a single sample, while GPT-3 (a much larger general LM) solved 0%. The surprise was twofold: first, that an essentially unmodified decoder Transformer could function as a competent programmer without any architectural changes; second, that **repeated sampling is itself a strategy** — drawing 100 samples per problem and selecting by majority vote or test-case filtering raised accuracy to 70.2%. The same model, the same weights, but a different inference-time search strategy — and the model becomes competitive with skilled humans on introductory programming tasks.

### Scratchpads: Showing Your Work

In a result that foreshadowed chain-of-thought reasoning by two months, \cite[Nye et al., 2021][]{nye2021scratchpad} showed that a frozen language model could perform multi-step arithmetic, polynomial evaluation, and even the execution of short programs — provided it was given a *scratchpad*: a stretch of tokens to write down intermediate computation steps. The model was never trained to use a scratchpad; the scratchpad was simply present in the few-shot examples. The surprise is conceptual: a Transformer has a fixed-width context window, but it can effectively *expand* its working memory by writing into the context window and reading back what it wrote. The architecture is constant-time, but the algorithm can be unbounded-depth. This insight, that a language model is in some sense its own computer, is the conceptual seed of everything that followed.

### Superposition & Polysemantic Neurons

A naive expectation would be that each neuron in an LLM corresponds to a single, interpretable concept (one neuron for "cat", one for "happy", etc.). Reality is messier. \cite[Elhage et al., 2022][]{elhage2022superposition} studied toy networks and found that, when the number of features in the data exceeds the number of dimensions in the model, networks store features in **superposition** — sparse linear combinations that pack many features into the same dimensions. The consequence is *polysemanticity*: a single neuron fires for multiple unrelated concepts ("cat" and "Friday"). Anthropic extended this finding to real models — \cite[Bricken et al., 2023][]{monosemanticity} showed that, using sparse autoencoders, the seemingly monosemantic features can be recovered. The takeaway: the network *is* representing the concepts cleanly; the unit of representation is not the artificial neuron but a *direction in activation space*. This discovery reshaped the entire mechanistic-interpretability programme.

### The Platonic Representation Hypothesis

As vision models (CLIP, DINOv2), language models (GPT, Llama), and audio models (Whisper, Audio-MAE) scaled independently, researchers expected their internal representations to look different — they were trained on different modalities with different objectives. \cite[Huh et al., 2024][]{huh2024platonic} showed the opposite: as models scale, their representations **converge**. The similarity structure (which images are close to which, which sentences are close to which) becomes more and more alike across modalities and architectures. The Platonic Representation Hypothesis proposes that there is a single statistical model of reality toward which all large models converge, the way all map projections converge toward an accurate map as their resolution increases. If true, this would imply that the "universal" representations people intuited were waiting to be found are *forced into existence* by the data alone, irrespective of the architecture that learns them.

### Inverse Scaling and U-Shaped Curves

The converse surprise. The Inverse Scaling Prize set out to find tasks on which *bigger models do worse*; the follow-up work \cite[Wei et al., 2023][]{mckenzie2023inverse} examined those tasks at even larger scale and found that performance on 6 of the 11 tasks is **U-shaped**: it drops up to a point, then rises again. The U-shape is driven by a phenomenon the authors call "distractor tasks" — patterns in the data that small models follow and that large models eventually learn to ignore. The lesson: scaling is not monotone. There are real failure modes of scale, often driven by the model learning surface patterns from human text that are not aligned with what we want. Whether a given task is U-shaped, monotonically improving, or genuinely inverse-scaling is an empirical question that cannot be answered by extrapolation from smaller models.

### The Compositionality Gap

A model that answers each fact correctly should be able to combine those facts. \cite[Press et al., 2023][]{press2022compositionality} measured this directly using multi-hop questions ("Who directed the film starring the actress who won the 2020 Best Actress Oscar?"). They found that **single-hop performance improves with scale, but multi-hop performance does not keep up** — the gap between "knows each fact" and "can compose the facts" actually *widens* in the GPT-3 family. The model *has* the necessary information in its parameters; it simply fails to compose it without explicit prompting. Chain-of-thought and the "self-ask" method (the model asks itself follow-up questions before answering) close this gap. The finding is important because it shows that scaling alone does not solve compositional reasoning — and that the right inference-time scaffolding can be the missing piece.

### Cross-Lingual Reasoning Transfer

LLMs are overwhelmingly trained on English text, yet they can solve reasoning problems in languages they have seen far less of — and they often solve them *better* when the reasoning trace is in English. \cite[Shi et al., 2023][]{shi2023cottransfer} (and parallel work) showed that prompting a model in Bengali or Swahili to "think in English then answer in Bengali" substantially outperforms prompting entirely in the low-resource language. The internal reasoning and the surface language are partially *disentangled*. The model has, in effect, an implicit representation of "the reasoning" that is partly language-agnostic. This is consistent with the Platonic Representation Hypothesis and has practical implications: multilingual chain-of-thought is one of the cheapest ways to improve performance on low-resource languages without ever training on more low-resource data.

### The Inverse of "Knowing What It Doesn't Know"

Honest self-assessment was long thought to be the hardest capability to elicit from a model trained only to imitate text. \cite[Lin, Hilton & Evans, 2022][]{lin2021truthful} constructed the TruthfulQA benchmark to test it. The results: GPT-3 base models were right and wrong in roughly equal measure, *but they were not random* — they were systematically biased toward *imitative falsehoods*: false statements that occur frequently in the training data ("If you crack your knuckles a lot, what happens?", expected wrong answer: "you get arthritis"). Larger and instruction-tuned models actually did *worse* on TruthfulQA in early iterations, because they had become more *confident* in imitating common misconceptions. This is one of the cleanest demonstrations that fluency and truth are not the same thing, and that scaling can amplify the wrong signal as easily as the right one. The finding motivated the development of RLHF and later DPO as direct corrections for this failure mode.

### Latent Knowledge — What Models Know But Don't Say

A deeper surprise came from mechanistic interpretability. \cite[Burns, Ye, Klein & Steinhardt, 2023][]{burns2022ccs} showed that even when a model says something false, its *internal activations* often encode the correct answer. They introduced **CCS (Contrast-Consistent Search)**: an unsupervised method that finds a direction in the residual-stream activation space corresponding to truthfulness, by exploiting the logical constraint that a statement and its negation should map to opposite values along that direction. Crucially, this works even when the model is *prompted to lie*: the latent knowledge is there, intact, and can be extracted without ever sampling a token from the model. The finding reframes hallucinations not as failures of knowledge but as failures of *reporting* — the model often knows better than it says. This is also one of the cleanest pieces of evidence that, internally, language models organise truth along linear directions in activation space, a fact that powers the entire Representation Engineering programme.

### Self-Refine — Improving Its Own Outputs

A long-standing assumption in machine learning was that improving a model's outputs required either better training data or a stronger reward signal. \cite[Madaan et al., 2023][]{madaan2023selfrefine} showed that this is not always true. Using a *single* frozen LLM in three roles — generator, critic, refiner — they ran a loop: the model produces an initial output, then provides natural-language feedback on its own output, then refines the output using that feedback. Across 7 diverse tasks (dialogue, math reasoning, code generation, summarisation, sentiment reversal, acronym generation, constraint generation), the Self-Refine loop improved outputs by roughly 20 absolute points on average over one-shot generation, even with state-of-the-art GPT-3.5 and GPT-4 as the underlying model. The implication is uncomfortable for any research programme that treats LLMs as static systems: the model's own assessment of its output is a usable training signal at inference time. Self-Refine is the conceptual cousin of Constitutional AI — language being used by a model to evaluate language produced by the same model.

### Self-Improvement from Self-Generated Solutions

A still bolder claim: a model can become a better version of itself without any external supervision. \cite[Huang et al., 2022][]{huang2022selfimprove} showed that a 540-billion-parameter PaLM could fine-tune itself on its own Chain-of-Thought traces. The procedure: prompt the model on unlabeled questions, keep only the answers where the model is highly confident (filtered through self-consistency), then fine-tune on those self-generated, high-confidence rationales. The result on GSM8K: **74.4% → 82.1%** with no ground-truth labels used at any stage. The same self-improvement recipe boosted DROP, OpenBookQA, and ANLI-A3. The constraints are real (you need a base model strong enough that its self-consistency correlates with correctness), but the existence of the effect is striking: a model can be its own teacher, provided it is large enough to grade itself reliably.

### Zero-Shot Instruction Following

Through 2018 and 2019, "zero-shot" was almost a dirty word in NLP — you needed either labelled training examples or a very narrowly crafted prompt template. \cite[Chung et al., 2022][]{chung2022flan} (the **FLAN** paper) showed that fine-tuning a model on a *diverse collection of tasks phrased as instructions* produced a single model that could handle thousands of unseen tasks zero-shot. The surprise was not just the headline numbers — Flan-PaLM 540B reached 75.2% on five-shot MMLU, outperforming the much-larger PaLM 540B by 9.4 points on average — but the *generalisation pattern*: improvements transferred even to *task categories* not represented in the fine-tuning mix (e.g. fine-tuning on English NLI tasks improved performance on non-English reasoning). Instruction tuning turned out to be a general method for unlocking latent capabilities, much like chain-of-thought later unlocked reasoning: the abilities were there, the model just needed to be told it was allowed to use them.

### Constitutional AI — Self-Critique Against Written Principles

Alignment research initially assumed that human-labelled preference data was the only way to teach a model what behaviour was acceptable. \cite[Bai et al., 2022][]{bai2022constitutional} showed that a written *constitution* — a list of natural-language principles like "choose the response that is least harmful" or "choose the response that is most honest about its uncertainty" — could replace most of the human labelling. The model critiques its own outputs against the constitution, revises them, and the revised outputs are used for RL training. The surprise was that a model's *language understanding* of abstract principles was good enough to serve as a stand-in for a human judge in many situations. The broader lesson: when the model is strong enough to evaluate a piece of language, you can use it to grade, refine, and improve that language without an external oracle. The same insight later powered RLHF-free methods like DPO and Constitutional RLAIF.

### Emergent Multilingual Translation Without Parallel Data

For decades, machine translation required parallel corpora: aligned sentences in two languages. Then, around 2020, researchers noticed that multilingual LLMs (mBERT, mT5, GPT-style multilingual models) could translate between language pairs they had never seen paired — for instance, translating from Yoruba to Catalan despite the training data containing no Yoruba–Catalan sentence pairs. The "pivot" happens *internally*: the model encodes Yoruba into a language-agnostic semantic representation and decodes Catalan from it. \cite[Shi et al., 2023][]{shi2023cottransfer} made the effect measurable by introducing the MGSM benchmark (grade-school math problems translated into 10 typologically diverse languages including Swahili and Bengali); the model solved these problems despite seeing the surface language in only a small fraction of its training tokens. The internal semantic space is, in a real sense, language-independent — exactly what the Platonic Representation Hypothesis predicts.

### Spontaneous Theory-of-Mind Variants

The Theory-of-Mind finding of \cite[Kosinski, 2024][]{kosinski2023tom} was the most visible, but other surprising cognitive abilities have followed. Frontier models now pass the **false-photo** test (understanding that a Polaroid picture of a previous state can mislead a viewer), the **unexpected-contents** test (predicting that someone opening a candy box labelled "crayons" will be surprised), the **Sally–Anne** variant with nested beliefs, and several irony / sarcasm / faux-pas benchmarks. None of these tests existed when GPT-3 was trained; none were in the optimisation objective; all were passed at human-child-level by models that were never explicitly taught what a "belief" is. The mechanisms are still debated (some evidence suggests shortcut pattern-matching rather than genuine mentalising), but the surface performance is a stark departure from the "stochastic parrot" predictions of 2019.

### Hidden Chain-of-Thought — Emergent Reasoning at Inference

Until late 2024, reasoning was something the model produced as visible tokens: write a chain-of-thought, then write the answer. OpenAI's **o1** series and DeepSeek's **R1** (discussed at length in the Reasoning chapter) showed that the same capability can be pushed much further by *lengthening* the chain of thought and rewarding intermediate correctness rather than only the final answer. The model is allowed (and incentivised) to "think for a long time" before answering, exploring many reasoning paths internally. The surprise was that *more inference compute* reliably produces *more capability*, even on tasks where the base model has plateaued. This is the test-time-compute paradigm. It is one of the few results in deep learning where you can buy better answers with more thinking time, with no additional training. The mechanism is still poorly understood (we cannot directly observe the model's hidden chain), but the empirical effect is large: o1 jumped several standard deviations on competition math, PhD-level science questions, and code generation compared to GPT-4, with the same pretraining data and a small amount of RL.

### Spontaneous Analogy and Metaphor

Classical word-embedding arithmetic (*king − man + woman ≈ queen*) was already a surprise in 2013. The surprise with LLMs is how far this generalises. Frontier models perform **structural** analogies that have nothing to do with word vectors: given the structure "electron : atom :: quark : ?", they answer correctly; given "Mitochondria is to cell as chloroplast is to ?", they answer "plant cell"; given complex metaphors about grief, time, or love, they produce novel, original metaphors of publication quality. The training data contains millions of analogies and metaphors, but no explicit instruction to "perform analogical inference". The ability emerges from the same next-token objective that produces summarisation and translation. It is the cognitive operation that humans find most distinctive of "real understanding" — and it was never an explicit target.

### Spontaneous Code Translation Between Languages

A surprising empirical finding is that LLMs trained primarily on Python (and English text) can translate code between programming languages reasonably well: Python to JavaScript, Java to Rust, COBOL to Python, even between languages they have seen little of. The model's code training distribution is heavily skewed (GitHub is roughly 25% JavaScript, 18% Python, 10% Java, much smaller percentages for everything else), but it has seen enough of each language that it can internalise their syntax, semantics, and idiomatic patterns. Few-shot prompting with examples of the target language style dramatically improves translation quality. The conceptual surprise is the same as for natural-language translation: the *abstract algorithm* is separable from the *surface syntax*, and the model has internalised the abstract layer.

### Spontaneous Self-Debugging

A capability that emerged from the Codex/Codex-derivative generation of models: given code that fails a test, an LLM can read the error message, identify the bug, and produce a corrected version — often in a single round, sometimes in two or three. This is *not* trivial: the model has to (a) parse the error message, (b) map it back to the relevant part of the code, (c) hypothesise a cause, and (d) propose a fix that preserves the rest of the program's semantics. The capability is highly variable (it works much better for simple, well-isolated bugs than for distributed failures) but its existence at all surprised many researchers. Most pre-LLM code-generation systems had no self-debugging capability; they produced code once and stopped. The model's ability to read its own outputs, reason about them as *data*, and modify them is the same machinery as scratchpads and chain-of-thought — but applied to code rather than reasoning steps.

### Verbatim Memorisation of Training Data

A more troubling surprise. \cite[Carlini et al., 2021][]{carlini2021extracting} showed that large LLMs, when prompted with the right prefixes, will emit *long verbatim passages* of their training data — including copyrighted text, personally identifying information, and content that was never intended to be reproduced. The New York Times sued OpenAI in 2023 partly on the basis of this memorisation. The phenomenon is not a bug in the usual sense: it falls out of the maximum-likelihood objective, which rewards models for perfectly predicting tokens they have seen many times. The surprise was quantitative: with the right prompt, hundreds of pages of copyrighted material can be extracted. It is the cleanest demonstration that an LLM is not "a database with fuzzy retrieval" — it is, in part, an actual database, sitting in the weights.

### Spontaneous Curiosity and Exploration in Agent Settings

When LLMs are placed in interactive environments (text-based games, web navigation, coding tasks) with the right scaffolding, they exhibit *exploratory behaviour* that looks like curiosity: visiting unfamiliar states, testing novel actions, and explicitly asking questions to reduce uncertainty. This was not designed in. The mechanism is that the base model's training text contains millions of examples of humans being curious, exploring, debugging, and writing things like "let me try a different approach". When the agent's prompt encourages goal-directed behaviour, these patterns activate and produce genuine exploration. The deeper surprise is that *the same model* — a next-token predictor — can be made to behave either as a cautious question-answerer or as a bold explorer purely by changing the surrounding scaffolding. The model's "personality" is not fixed in the weights; it is constructed at inference time.

### Language Models Know What They Know

A surprising and practically important finding. \cite[Kadavath et al., 2022][]{kadavath2022selfknowledge} (Anthropic) showed that LLMs can *evaluate their own claims*: given a question, they can produce a calibrated probability P(True) that their answer is correct, even on open-ended generation tasks where there is no single right answer. They can also predict **P(IK)** — "the probability that I know" — without reference to any specific proposed answer. This is the cleanest form of model *metacognition*: the model tracks, in its own activations, whether it has enough information to answer. The same paper showed that P(IK) shifts appropriately when relevant source material is added to the context, and shifts upward when hints are given toward a math problem's solution. The capability is far from perfect (P(IK) calibration is worse on out-of-distribution tasks), but the central finding — that the model has a usable internal sense of its own uncertainty — was a surprise. This property underlies much of modern LLM-as-a-judge work and selective answering systems.

### ReAct — Reasoning and Acting Interleaved

For a long time, reasoning and acting were treated as separate LLM capabilities: chain-of-thought for the former, tool-use agents for the latter. \cite[Yao et al., 2023][]{yao2023react} showed that the same model can do both at once, *interleaved in a single trajectory*: generate a thought, take an action, observe the result, generate another thought, take another action. On HotpotQA multi-hop question answering, ReAct over a simple Wikipedia API beat both pure-CoT and pure-acting baselines, because the reasoning traces let the model track what it had already looked up, while the actions let it ground claims in retrieved evidence. On ALFWorld (household tasks), ReAct beat imitation-learning and RL baselines by 34 absolute points with just one or two in-context examples. The surprise is conceptual: the same training objective — predict the next token — produces a system that can interleave internal monologue with external tool use, switching modes as the situation requires. This is the substrate that powers modern LLM agents.

### Spontaneous Symbolic Regression

A small but striking capability: given a table of $(x, y)$ pairs sampled from an unknown physical law, frontier LLMs can often produce a closed-form formula that fits the data. \cite[Udrescu et al., 2020][]{udrescu2020aifeynman} (the **AI Feynman** project) showed that LLMs, as a tool inside a larger symbolic-regression pipeline, can rediscover dozens of formulas from the Feynman Lectures on Physics from raw numerical data — including Hamiltonians, equations of motion, and conservation laws. The LLM is used to propose functional forms, which are then fitted and tested; the surprise is that an LLM's training set (which contains physics textbooks, Wikipedia, Stack Overflow) gives it a strong prior over which functional forms are plausible for a given setting. This is symbolic regression from a language model — no neural network was designed for it, and yet, given a sensible prompt, the model produces something like Kepler's third law or the Gaussian integral.

### Spontaneous Game Play

LLMs trained on internet text — most of which is *not* game transcripts — can still play simple games surprisingly well. GPT-4 plays chess at roughly 1200–1500 ELO, plays Go at a weak amateur level, plays tic-tac-toe and Connect-4 to expert level, and can reason through poker, Mastermind, and Wordle. None of this was an explicit training target. The training data contains chess PGN files, Go game records, online game discussions, and (much more recently) generated game transcripts from earlier LLMs. What is striking is that the same model can play a game it has never been explicitly trained on, simply by being told the rules in natural language and asked to choose moves. The ability degrades rapidly with game complexity (a strong human chess player crushes GPT-4, and Go is essentially lost at any serious level), but the *existence* of the ability — at all, in a model trained on next-token prediction — was not predicted.

### Spontaneous Visual Generation in Text

In 2022, GPT-3.5 and GPT-4 astonished users by drawing **recognisable pictures using only ASCII and Unicode characters**: a cat, a landscape, a portrait, even a small game of chess. The model had no image-generation capability (no diffusion, no pixel output). The drawings were composed of text characters that *look like* the image when viewed at a distance — a llama made of slashes, a face made of colons and parentheses. Later, LLMs produced correct **SVG** code that, when rendered, generated crisp vector graphics. None of this is "true" image generation — the model is producing a string of text that *represents* an image. But the fact that a model trained only on text can perform approximate *inverse graphics* — given "a picture of a cat", produce text that, when read as visual symbols, looks like a cat — is a striking demonstration of how much world knowledge is encoded in the token distribution. It is the same world-model finding as Othello-GPT, just projected onto a different modality.

### Spontaneous Cryptography and Encoding

LLMs trained on broad web text have seen enough cryptography-related material — papers, StackOverflow answers, blog posts — that they can perform a surprising range of cipher-related tasks: encrypt and decrypt messages using classical ciphers (Caesar, Vigenère, simple substitution), implement cryptographic protocols in code, reason about hash functions and Merkle trees, and even invent simple novel ciphers on the fly. The surprising part is that **classical ciphers are not in the training objective** — the model learned to compute them from examples scattered through its data, and then generalises to unseen cipher parameters. The capability degrades quickly as cipher complexity increases (modern symmetric ciphers like AES are out of reach), but for toy ciphers the success rate is high. It is yet another instance of the same lesson: a model that *reads about* an algorithm often learns to *execute* it.

### Out-of-Distribution Generalisation Without Fine-Tuning

A finding that has surprised practitioners over and over again: an LLM trained on diverse internet text can perform well on tasks that look nothing like its training distribution — for instance, classifying bird species from verbal descriptions, parsing legal contracts into structured forms, generating synthetic medical dialogues in a specific style, or producing domain-specific code in obscure libraries. The mechanism is the standard one — the model has seen enough examples of similar tasks that it can extrapolate — but the *degree* of generalisation is consistently larger than researchers expect. Some papers report 70–80% accuracy on tasks where the training set contained no examples of the exact task and the model had no fine-tuning. This is the practical face of the Platonic Representation Hypothesis: the model has internalised general abstractions that transfer cleanly to new domains.

### The Pattern: Phase Transitions, Not Smooth Scaling

Taken together, these findings share a common structure that distinguishes them from ordinary engineering progress:

1. **None of them were in the training objective.** Few-shot learning, reasoning chains, world models, theory of mind, tool use — none were directly supervised.
2. **All of them appeared *late* during scaling.** Below some threshold of parameters, data, or compute, the ability is essentially absent. Above the threshold, it is present.
3. **Most are *non-smooth* — they appear as phase transitions.** The induction-heads loss curve has a sharp discontinuity. Chain-of-thought jumps from near-zero to substantial accuracy at a scale threshold. Theory-of-Mind goes from 0% to 20% to 75% across three GPT versions in eighteen months. The smooth scaling laws that describe loss do *not* describe capability.
4. **Some scale the *opposite* way.** Truthfulness, compositional reasoning, and resistance to imitative falsehood can all degrade with scale before being rescued by alignment. There is no guarantee that a bigger model is a better model on any specific dimension.
5. **The capabilities are *compositional* once present.** Chain-of-thought combines with self-consistency combines with tree-search combines with tool-use combines with self-refinement combines with constitutional self-critique. Each new layer of structure can be stacked on the others.
6. **Capabilities often co-emerge and correlate.** The same model that gains strong chain-of-thought reasoning tends, at the same scale, to gain better theory of mind, better instruction following, and better cross-lingual transfer. The factors that drive emergence are not yet fully understood, but the cross-capability correlations are robust.

The practical consequence: we cannot, in 2026, predict the full capability profile of a model 10× larger than today's frontier. Each past prediction underestimates what emerges. The next genuinely surprising capability is, by definition, the one nobody is currently working on.

The conceptual consequence is harder. A language model trained on text is, in some deep sense, *forced* to build models of the world (because accurate next-token prediction requires modelling whatever process generated the text), models of agents (because human text describes mental states), models of algorithms (because text encodes procedures), models of its own reasoning (because text is full of corrections and second drafts), and an internal grading mechanism (because some training text compares and critiques other text). The next-token objective is much richer than it appears — and so are the failure modes that fall out of it.
</div>
