name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies (smoke)
        run: |
          sudo apt-get update
          sudo apt-get install -y ack-grep

      - name: Run Smoke Tests
        run: |
          sudo Xvfb :99 -ac &
          export DISPLAY=:99
          bash tests/smoke_tests

  playwright-browsers:
    needs: smoke-tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          echo "Installing dependencies for ${RUNNER_OS}"
          if [ "${RUNNER_OS}" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y chromium-browser x11-apps docker.io
            sudo systemctl start docker || true
            sudo usermod -aG docker $USER || true
          elif [ "${RUNNER_OS}" = "macOS" ]; then
            brew update
            brew install --cask docker || true
            # On macOS GitHub runners, Docker Desktop won’t auto-start;
            # for CI we can use Colima (a lightweight Docker replacement)
            brew install colima || true
            colima start || true
          else
            echo "Unsupported OS: ${RUNNER_OS}"
            exit 1
          fi

      - name: Ensure PHP Installed (if required by tests)
        run: |
          if ! command -v php >/dev/null 2>&1; then
            echo "PHP not found. Installing..."
            if [ "${RUNNER_OS}" = "Linux" ]; then
              sudo apt-get install -y php-cli
            elif [ "${RUNNER_OS}" = "macOS" ]; then
              brew install php
            fi
          fi

      - name: Install Playwright (and browsers)
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install
        shell: bash

      - name: Run Playwright Tests
        run: |
          echo "Running tests on ${RUNNER_OS}"
          if [ "${RUNNER_OS}" = "Linux" ]; then
            sudo Xvfb :99 -ac &
            export DISPLAY=:99
            bash run_tests --no-smoke-tests --browser=chromium
          elif [ "${RUNNER_OS}" = "macOS" ]; then
            # Run Chromium and WebKit sequentially
            bash run_tests --no-smoke-tests --browser=chromium || true
            bash run_tests --no-smoke-tests --browser=webkit
          else
            echo "Unsupported runner: ${RUNNER_OS}"
            exit 1
          fi

      - name: Create a new version
        if: ${{ success() }}
        run: |
          echo "Creating new version"
          git tag ${{ github.run_number }} || true
          git push origin --tags || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
