name: Run Tests and Tag Version

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache Chromium and Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache
          /usr/local/bin/chromium
          ~/.asanai_test_env
        key: ${{ runner.os }}-chromium-${{ hashFiles('package-lock.json', 'run_tests') }}
        restore-keys: |
          ${{ runner.os }}-chromium-

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser x11-apps

    - name: Run Tests
      run: |
        sudo Xvfb :99 -ac &
        export DISPLAY=:99
        bash run_tests

    - name: Create a new version
      if: ${{ success() }}
      run: |
        echo "Creating new version"
        git tag ${{ github.run_number }} || true
        git push origin --tags || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
