name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser x11-apps

      - name: Run Smoke Tests
        run: |
          sudo Xvfb :99 -ac &
          export DISPLAY=:99
          bash tests/smoke_tests

  playwright:
    runs-on: ubuntu-latest
    needs: smoke-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser x11-apps

      - name: Run Playwright Tests (Chromium)
        run: |
          sudo Xvfb :99 -ac &
          export DISPLAY=:99
          bash run_tests --no-smoke-tests --browser=chromium

      - name: Run Playwright Tests (Firefox)
        run: |
          sudo Xvfb :99 -ac &
          export DISPLAY=:99
          bash run_tests --no-smoke-tests --browser=firefox

      - name: Create a new version
        if: ${{ success() }}
        run: |
          echo "Creating new version"
          git tag ${{ github.run_number }} || true
          git push origin --tags || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
